using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;
namespace Aether {
 [DefaultExecutionOrder(10000)]
 public class AirahTest:MonoBehaviour {
  Game game;string output;int failures;bool view;Vector3 cameraPosition,cameraTarget;float began;readonly List<string> reports=new List<string>();
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){if(Environment.GetCommandLineArgs().Contains("-aetherAirahTest"))new GameObject("Airah verification").AddComponent<AirahTest>();}
  void Check(bool ok,string message){var text=(ok?"PASS ":"FAIL ")+message;reports.Add(text);Debug.Log("AIRAH TEST "+text);if(!ok)failures++;File.WriteAllLines(Path.Combine(output,"checks.txt"),reports);}
  void LateUpdate(){if(view&&game){game.cam.transform.position=cameraPosition;game.cam.transform.LookAt(cameraTarget);}if(began>0&&Time.realtimeSinceStartup-began>700){File.WriteAllText(Path.Combine(output,"test-result.txt"),"TIMEOUT failures="+failures);Application.Quit(2);}}
  IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return null;}
  void Place(int n,float speed=0){var v=game.player;v.body.position=game.track.points[n]+Vector3.up*.65f;v.body.rotation=Quaternion.LookRotation(game.track.Forward(n));v.transform.SetPositionAndRotation(v.body.position,v.body.rotation);v.body.linearVelocity=game.track.Forward(n)*speed;v.body.angularVelocity=Vector3.zero;v.offTrackTime=v.wrongWayTime=v.trappedTime=0;v.stun=v.shield=0;v.lastPoint=n;v.progress=n;v.ResetFinishSample();Physics.SyncTransforms();}
  IEnumerator Measure(string name){var times=new List<float>();float start=Time.realtimeSinceStartup;while(Time.realtimeSinceStartup-start<10){times.Add(Time.unscaledDeltaTime);yield return null;}times.Sort();float avg=times.Count/times.Sum(),low=1/times[Mathf.Min(times.Count-1,(int)(times.Count*.99f))];string text=name+" average="+avg.ToString("F1")+" fps; 1% slow frame="+low.ToString("F1")+" fps; "+Screen.width+"x"+Screen.height;reports.Add(text);Debug.Log("AIRAH PERF "+text);File.WriteAllLines(Path.Combine(output,"checks.txt"),reports);}
  IEnumerator Start(){
   output=Path.GetFullPath(Application.dataPath+"/../../Evidence/Airah");Directory.CreateDirectory(output);began=Time.realtimeSinceStartup;yield return new WaitForSeconds(1);game=FindAnyObjectByType<Game>();game.ChooseDevice(false);game.rushMode=game.stuntMode=false;game.mapIndex=TrackWorld.AirahMap;game.aiCount=19;game.laps=1;game.menu="Game Setup";yield return Shot("01-map-selection");game.StartRace();yield return new WaitUntil(()=>game.state==Game.State.Race);
   var track=game.track;game.player.manualTest=true;Check(track.IsAirah&&game.racers.Count==20,"New circuit loads with 20 racers");Check(track.length>8000&&track.airahMaxHeight-track.airahMinHeight>350,"Huge route and elevation variation: "+track.length.ToString("F0")+"m, climb "+(track.airahMaxHeight-track.airahMinHeight).ToString("F0")+"m");Check(track.airahTrees>8000&&track.airahRocks>3000,"Dense instanced nature: "+track.airahTrees+" trees, "+track.airahRocks+" rocks");Check(track.GetComponentsInChildren<TricycleTraffic>().Length==18,"18 physical civilian cars");Check(track.tiles.Count>=15,"Boosters, jumpers and ramps connected");Check(track.GetComponentsInChildren<TextMesh>().Any(t=>t.text.Contains("made by Aljay Leodones")),"Developer Easter egg sign");
   int missing=0,buried=0;float maxGrade=0;for(int i=0;i<TrackWorld.Count;i++){if(track.AirahGap(i))continue;var p=Vector3.Lerp(track.points[i],track.points[(i+1)%TrackWorld.Count],.5f);if(!Physics.Raycast(p+Vector3.up*1.8f,Vector3.down,out var hit,4,1))missing++;else if(hit.point.y>p.y+.5f)buried++;maxGrade=Mathf.Max(maxGrade,Mathf.Abs(track.Forward(i).y));}
   Check(missing==0,"Road collision continuous outside bridge gap (missing="+missing+")");Check(buried==0,"Terrain does not cover road (buried="+buried+")");Check(maxGrade<.30f,"Driveable maximum grade "+maxGrade.ToString("F2"));
   var middle=(track.points[34]+track.points[35])*.5f;Check(!Physics.Raycast(middle+Vector3.up*2,Vector3.down,12,1),"Broken bridge has a real open gap");
   yield return Shot("02-start");view=true;cameraPosition=new Vector3(2100,1480,-1950);cameraTarget=new Vector3(0,160,120);game.cam.fieldOfView=56;yield return new WaitForSeconds(.3f);yield return Shot("03-mountain-overview");
   foreach(int n in new[]{33,160,250,350}){cameraPosition=track.points[n]-track.Forward(n)*100+track.Right(n)*105+Vector3.up*67;cameraTarget=track.points[(n+4)%480];yield return new WaitForSeconds(.25f);yield return Shot("04-scenery-"+n);}
   var egg=GameObject.Find("Airah developer Easter egg").transform;cameraPosition=egg.position-egg.forward*10+Vector3.up*3.2f;cameraTarget=egg.position+Vector3.up*3.2f;yield return new WaitForSeconds(.2f);yield return Shot("04-developer-sign");cameraPosition=track.points[254]+Vector3.up*8;cameraTarget=cameraPosition-GameObject.Find("Sun").transform.forward*1000;yield return new WaitForSeconds(.2f);yield return Shot("04-afternoon-sun");
   view=false;game.cam.fieldOfView=53;Place(220);yield return new WaitForSeconds(2);Check(track.GetComponent<AirahForestRenderer>().visibleInstances>100,"Visible forest instances submitted: "+track.GetComponent<AirahForestRenderer>().visibleInstances+"; GPU instancing "+SystemInfo.supportsInstancing);yield return Measure("PC, 20 racers");game.ChooseDevice(true);yield return new WaitForSeconds(1);yield return Shot("05-phone-controls");yield return Measure("Phone quality on desktop, 20 racers");game.ChooseDevice(false);
   // Drive into the takeoff deck from modest approach speed, without teleporting across the gap.
   Place(28,28);game.player.player=false;game.player.manualTest=false;int returns=game.player.automaticReturns;bool airborne=false,landed=false;float start=Time.realtimeSinceStartup;
   while(Time.realtimeSinceStartup-start<20){int n=track.Nearest(game.player.transform.position);if(n>=33&&n<=36&&game.player.grounded==0){if(!airborne)yield return Shot("06-broken-bridge-flight");airborne=true;}if(n>=37&&n<50&&game.player.grounded>=2){landed=true;break;}yield return null;}
   Check(airborne&&landed&&game.player.automaticReturns==returns,"Physics-driven broken bridge jump reaches landing deck");yield return Shot("07-bridge-landing");
   game.player.manualTest=true;game.player.body.position=middle-Vector3.up*25;game.player.transform.position=game.player.body.position;Physics.SyncTransforms();Debug.Log("AIRAH RECOVERY before body="+game.player.body.position+" transform="+game.player.transform.position);game.player.Recover();yield return new WaitForFixedUpdate();Check(track.Nearest(game.player.body.position)==27,"Missed jump returns to boosted approach (actual="+track.Nearest(game.player.body.position)+")");
   if(Environment.GetCommandLineArgs().Contains("-aetherAirahQuick")){File.WriteAllText(Path.Combine(output,"quick-result.txt"),"failures="+failures+"\n"+string.Join("\n",reports));Application.Quit(failures==0?0:1);yield break;}
   // Full uninterrupted route traversal and ordered checkpoint completion.
   Place(2);game.player.progress=2;game.player.circuitCheckpoint=0;game.player.completedLaps=0;game.player.manualTest=false;game.player.player=false;start=Time.realtimeSinceStartup;float next=0;
   while(!game.player.finished&&Time.realtimeSinceStartup-start<450){if(Time.realtimeSinceStartup-start>next){next+=20;Debug.Log("AIRAH DRIVE point="+track.Nearest(game.player.transform.position)+" progress="+game.player.progress+" gate="+game.player.circuitCheckpoint+" speed="+game.player.speed+" returns="+game.player.automaticReturns);}yield return null;}
   Check(game.player.finished,"Full physics-driven mountain lap completes all ordered checkpoints");yield return new WaitForSeconds(2);yield return Shot("08-lap-complete");File.WriteAllText(Path.Combine(output,"test-result.txt"),"failures="+failures+"\n"+SystemInfo.graphicsDeviceName+"\n"+SystemInfo.processorType+"\n"+string.Join("\n",reports));Debug.Log("AIRAH COMPLETE failures="+failures);Application.Quit(failures==0?0:1);
  }
 }
}
