using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;
namespace Aether {
 public class DetailTest:MonoBehaviour {
  Game game;int failures;float began;string output;bool drive;float report;HashSet<string> used=new HashSet<string>();
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){if(Environment.GetCommandLineArgs().Contains("-aetherDetailTest"))new GameObject("Detail verification").AddComponent<DetailTest>();}
  void Check(bool ok,string label){Debug.Log("DETAIL "+(ok?"PASS ":"FAIL ")+label);if(!ok)failures++;}
  void Update(){if(began>0&&Time.realtimeSinceStartup-began>420){File.WriteAllText(Path.Combine(output,"result.txt"),"TIMEOUT failures="+failures);Application.Quit(2);}if(drive&&game&&game.player){game.player.SendMessage("DriveStuntAI");if(Time.time>report){report=Time.time+10;Debug.Log("DETAIL AI "+string.Join(" | ",game.racers.Select(v=>v.driver+": z="+(int)v.transform.position.z+" cp="+v.stuntCheckpoint+" returns="+v.automaticReturns)));}}}
  IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return null;}
  void Place(Vehicle v,Vector3 p,Quaternion q){v.body.position=p;v.body.rotation=q;v.transform.SetPositionAndRotation(p,q);v.body.linearVelocity=v.body.angularVelocity=Vector3.zero;v.shield=v.stun=v.rolloverLock=0;v.offTrackTime=v.wrongWayTime=v.trappedTime=0;Physics.SyncTransforms();}
  void MapCheck(string label){used.UnionWith(game.track.detailTypes);Check(game.track.detailPropCount>30,label+" has populated downloaded scenery ("+game.track.detailPropCount+" instances, "+game.track.detailTypes.Count+" types)");}
  IEnumerator MenuCheck(string mode){game.state=Game.State.Results;Time.timeScale=0;yield return Shot(mode+"-results");game.MainMenu();yield return null;Check(game.state==Game.State.Menu&&game.menu=="Play"&&!game.rushMode&&!game.stuntMode&&game.player==null&&game.racers.Count==0&&Time.timeScale==1,mode+" Main Menu cleans up race and restores time");}
  IEnumerator Start(){output=Path.GetFullPath(Application.dataPath+"/../../Evidence/DetailUpdate");Directory.CreateDirectory(output);began=Time.realtimeSinceStartup;yield return new WaitForSeconds(1);game=FindAnyObjectByType<Game>();game.ChooseDevice(false);game.menu="Garage";
   for(int i=1;i<=10;i++){var tex=PaintStyles.Texture(i);Check(tex&&tex.width>=1024&&tex.height>=1024,"Generated texture "+PaintStyles.Names[i]);var c=new SavedCar{paintStyle=i,paint=14};var loaded=JsonUtility.FromJson<SavedCar>(JsonUtility.ToJson(c));Check(loaded.paintStyle==i&&loaded.paint==14,"Paint/color serialization "+i);game.CurrentCar.paintStyle=i;game.CurrentCar.paint=14;game.SendMessage("Changed");yield return new WaitForSeconds(.25f);yield return Shot("paint-"+PaintStyles.Files[i]);}
   for(int car=0;car<10;car++){var m=ModelLibrary.Create(CarSpec.All[car].name);CarParts.Apply(m,new SavedCar{body=car,paintStyle=1,paint=6});var painted=m.GetComponentsInChildren<MeshRenderer>().Where(r=>r.name=="Paint").ToArray();Check(painted.Length>0&&painted.All(r=>r.sharedMaterial.shader.name=="Aether/Paint"&&r.sharedMaterial.GetTexture("_MainTex")),"Texture wraps car "+CarSpec.All[car].name);Destroy(m);}
   game.CurrentCar.paintStyle=1;game.SendMessage("Changed");game.stuntAiCount=9;game.menu="Play";game.stuntTab=true;yield return Shot("stunts-setup");game.StartStunts();yield return new WaitUntil(()=>game.state==Game.State.Race);var carPlayer=game.player;carPlayer.manualTest=true;
   Check(game.racers.Count==10,"Stunts spawns player plus nine AI");MapCheck("Heartstopper");foreach(var v in game.racers){v.manualTest=true;v.body.isKinematic=true;}
   foreach(float z in new[]{520f,850f,1190f,1370f,2700f}){Place(carPlayer,game.track.StuntPosition(z)+Vector3.up*.5f,Quaternion.LookRotation(game.track.StuntPosition(z+2)-game.track.StuntPosition(z-2)));yield return new WaitForSeconds(.5f);var normal=Vector3.Cross((game.track.StuntPosition(z+2)-game.track.StuntPosition(z-2)).normalized,Vector3.right);var screen=game.cam.WorldToViewportPoint(carPlayer.transform.position);var ahead=game.cam.WorldToViewportPoint(game.track.StuntPosition(z+40));Check(Vector3.Dot(game.cam.transform.position-carPlayer.transform.position,normal)>6&&screen.z>0&&screen.x>.15f&&screen.x<.85f&&screen.y>.15f&&screen.y<.85f&&ahead.y>.1f&&ahead.y<.95f,"Downhill roof and forward road in view at "+z);yield return Shot("downhill-"+z);}
   // Fresh start for a continuous real physics run, without teleports or simulated checkpoints.
   game.StartStunts();yield return new WaitUntil(()=>game.state==Game.State.Race);carPlayer=game.player;carPlayer.manualTest=true;drive=true;float started=Time.realtimeSinceStartup;bool descent=false,air=false,landing=false;int frames=0;float elapsed=0;
   while(!carPlayer.finished&&Time.realtimeSinceStartup-started<180){frames++;elapsed+=Time.unscaledDeltaTime;if(carPlayer.transform.position.z>550&&!descent){descent=true;yield return Shot("stunts-live-descent");}if(carPlayer.transform.position.z>1550&&!air){air=true;yield return Shot("stunts-live-jump");}if(carPlayer.stuntCheckpoint>=3&&!landing){landing=true;yield return Shot("stunts-live-landing");}yield return null;}
   drive=false;Check(carPlayer.finished,"Continuous Stunts race with nine AI reaches finish");Check(game.racers.Skip(1).All(v=>v.stuntCheckpoint>=2),"Every opponent completes the first descent");Check(game.racers.Skip(1).Count(v=>v.stuntCheckpoint>=3)>=5,"At least five AI clear the first island jump");Debug.Log("DETAIL PERFORMANCE Stunts frames="+frames+" seconds="+elapsed+" averageFPS="+frames/Mathf.Max(.1f,elapsed));yield return new WaitForSecondsRealtime(3);yield return MenuCheck("stunts");
   game.StartRush(0);yield return new WaitUntil(()=>game.state==Game.State.Race);MapCheck("Coastal Rush");foreach(var v in game.racers){v.manualTest=true;v.body.isKinematic=true;}var carFx=game.player;carFx.body.isKinematic=false;carFx.enforceTrackBounds=false;
   Place(carFx,new Vector3(0,5.4f,180),Quaternion.identity);carFx.throttle=1;yield return new WaitForSeconds(.5f);Check(carFx.smokeIntensity>.05f,"Acceleration creates wheelspin smoke");yield return Shot("fx-launch");
   Place(carFx,new Vector3(0,5.4f,210),Quaternion.identity);carFx.body.linearVelocity=Vector3.forward*48;carFx.throttle=-1;yield return new WaitForSeconds(.3f);Check(carFx.smokeIntensity>.2f,"High speed braking creates smoke");yield return Shot("fx-braking");
   Place(carFx,new Vector3(0,5.4f,260),Quaternion.identity);carFx.body.linearVelocity=Vector3.forward*40+Vector3.right*6;carFx.throttle=1;carFx.drift=true;yield return new WaitForSeconds(.3f);Check(carFx.smokeIntensity>.2f,"Drifting creates tire smoke");yield return Shot("fx-drift");carFx.drift=false;
   Place(carFx,new Vector3(0,5.4f,330),Quaternion.identity);carFx.body.linearVelocity=Vector3.forward*55;carFx.boost=2;yield return new WaitForSeconds(.65f);Check(carFx.boostGhostCount>=3&&carFx.GetComponentsInChildren<TrailRenderer>().Count(t=>t.name.StartsWith("Boost aura")&&t.positionCount>3)>=2,"Boost emits aura ribbons and multiple car afterimages");yield return Shot("fx-boost");carFx.boost=0;yield return new WaitForSeconds(.6f);Check(carFx.GetComponentsInChildren<SpeedAfterimage>().Length==0,"Afterimages fade out after boost");yield return MenuCheck("rush");
   for(int theme=1;theme<3;theme++){game.StartRush(theme);yield return new WaitUntil(()=>game.state==Game.State.Race);MapCheck("Rush "+theme);game.player.manualTest=true;yield return Shot("rush-map-"+theme);game.MainMenu();yield return null;}
   game.aiCount=2;for(int map=0;map<3;map++){game.mapIndex=map;game.StartRace();yield return new WaitUntil(()=>game.state==Game.State.Race);MapCheck(TrackWorld.Names[map]);game.player.manualTest=true;yield return Shot("circuit-map-"+map);if(map==2)yield return MenuCheck("circuit");else{game.MainMenu();yield return null;}}
   Check(used.Count==58,"All 58 downloaded prop types actually placed across seven maps: "+used.Count);File.WriteAllLines(Path.Combine(output,"placed-props.txt"),used.OrderBy(s=>s));File.WriteAllText(Path.Combine(output,"result.txt"),"failures="+failures+" placedTypes="+used.Count);Debug.Log("DETAIL COMPLETE failures="+failures);Application.Quit(failures==0?0:1);
  }
 }
}
