using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
namespace Aether {
 public partial class Game:MonoBehaviour {
  public enum State {Menu,Countdown,Race,Pause,Results}
  public State state=State.Menu;public TrackWorld track;public List<Vehicle> racers=new List<Vehicle>();public Vehicle player;public Camera cam;public int laps=3,aiCount=11,mapIndex,selectedCar,paintIndex,wheelIndex,windowIndex,engineLevel,tireLevel,brakeLevel,difficulty=1;public bool powerups=true;public float raceTime,cameraShake,volume=.55f;public float difficultyFactor=>new[]{.72f,.88f,1.04f}[difficulty];
  public static readonly Color[] Paints={new Color(0.0941f,0.1294f,0.1765f),new Color(0.1255f,0.702f,0.702f),new Color(0.749f,0.1686f,0.4588f),new Color(0.9412f,0.5647f,0.1804f),new Color(0.8078f,0.851f,0.8902f),new Color(0.3412f,0.251f,0.6784f),new Color(0.7961f,0.0902f,0.2196f),new Color(0.9608f,0.4353f,0.3843f),new Color(1.0f,0.5137f,0.1059f),new Color(0.9569f,0.8118f,0.2157f),new Color(0.6235f,0.8118f,0.2196f),new Color(0.1373f,0.4353f,0.2824f),new Color(0.498f,0.8824f,0.7373f),new Color(0.0863f,0.4902f,0.5333f),new Color(0.2902f,0.6824f,0.902f),new Color(0.1922f,0.3529f,0.8588f),new Color(0.1098f,0.1922f,0.3647f),new Color(0.6706f,0.5725f,0.8941f),new Color(0.4039f,0.2392f,0.502f),new Color(0.8863f,0.3373f,0.6f),new Color(0.8902f,0.6902f,0.7176f),new Color(0.7137f,0.4118f,0.251f),new Color(0.5882f,0.502f,0.2941f),new Color(0.7608f,0.6824f,0.549f),new Color(0.6431f,0.7059f,0.749f),new Color(0.3373f,0.4039f,0.4549f),new Color(0.0627f,0.098f,0.1373f),new Color(0.9333f,0.9333f,0.9294f),new Color(0.898f,0.851f,0.7216f),new Color(0.6314f,0.8471f,0.898f),new Color(0.4118f,0.4706f,0.2353f),new Color(0.3373f,0.2392f,0.2039f)};
  public static readonly string[] PaintNames={"Graphite","Lagoon","Berry","Sunburst","Pearl","Iris","Crimson","Coral","Tangerine","Lemon","Lime","Forest","Mint","Teal","Sky","Cobalt","Navy","Lavender","Plum","Rose","Blush","Copper","Bronze","Sand","Silver","Slate","Ink","Snow","Cream","Ice","Olive","Chocolate"};
  public string menu="Play";GameObject showroom,preview;float countdown=3.8f,orbit=-35;Vector3 cameraVel;string message="";float messageTimer;GUIStyle text,title,button,small;Texture2D pixel;public int credits=1200;bool loading;int finishedCount;List<Pickup> boxes=new List<Pickup>();bool testing;float testTimer;int testStage;string evidencePath;State beforePause;int testMap;float testFps;int testFrames;
  string[] botNames={"Sir Skids-a-Lot","Brake Expectations","Wheelie Nelson","Clutch Potato","Tofu Fast","Bumper Dumpling","Oops All Boost","Driftwood Mac","Lord of the Rims","Pasta La Vista","No Turn Intended","Vin Diesel-ish","Duke of Donuts","Tire-d Already","Waffle Throttle","Major Speedbump","Spud Racer","Jean Clutch Van Damme","Biscuit Bandit"};
  void Awake(){Application.targetFrameRate=120;QualitySettings.vSyncCount=0;Physics.defaultSolverIterations=10;Physics.defaultSolverVelocityIterations=4;Time.fixedDeltaTime=1/100f;if(!Application.isMobilePlatform)Screen.SetResolution(1600,900,FullScreenMode.Windowed);testing=Environment.GetCommandLineArgs().Any(a=>a.StartsWith("-aether"));Load();cam=Camera.main;if(!cam){cam=new GameObject("Main Camera").AddComponent<Camera>();cam.tag="MainCamera";cam.gameObject.AddComponent<AudioListener>();}cam.nearClipPlane=.08f;cam.farClipPlane=3000;cam.fieldOfView=53;cam.allowHDR=true;cam.backgroundColor=new Color(.16f,.2f,.3f);RenderSettings.ambientLight=new Color(.66f,.72f,.87f);var sun=new GameObject("Sun").AddComponent<Light>();sun.type=LightType.Directional;sun.transform.rotation=Quaternion.Euler(42,-35,0);sun.intensity=1.15f;sun.shadows=LightShadows.Soft;QualitySettings.shadowDistance=150;QualitySettings.shadows=ShadowQuality.All;QualitySettings.antiAliasing=4;cam.gameObject.AddComponent<Presentation>();Physics.IgnoreLayerCollision(8,9);Physics.IgnoreLayerCollision(9,9);Physics.IgnoreLayerCollision(9,10);MakeShowroom();string[] args=Environment.GetCommandLineArgs();testing=args.Any(a=>a.StartsWith("-aether"));evidencePath=Application.dataPath+"/../../Evidence";InitializePlatform();}
  void Load(){LoadGarage();LoadInventory();}
  void Start(){var editorPreview=GameObject.Find("Editor Preview");if(editorPreview)Destroy(editorPreview);}
  void Save(){StoreCar();if(testing)return;PlayerPrefs.SetString("garage-v2",JsonUtility.ToJson(garage));PlayerPrefs.SetInt("credits",credits);PlayerPrefs.SetFloat("volume",volume);if(inventory!=null)PlayerPrefs.SetString("rush-inventory-v1",JsonUtility.ToJson(inventory));PlayerPrefs.Save();}
  void MakeShowroom(){
   showroom=new GameObject("Garage display");RenderSettings.fog=false;var sky=new Material(Shader.Find("Aether/Sky"));sky.SetColor("_Top",new Color(.018f,.028f,.045f));sky.SetColor("_Horizon",new Color(.045f,.065f,.095f));RenderSettings.skybox=sky;
   var floor=TrackWorld.Cube("Garage floor",new Vector3(0,-.23f,0),new Vector3(150,.4f,150),ModelLibrary.Material("garagefloor",new Color(.035f,.05f,.075f),0,0),true);floor.transform.SetParent(showroom.transform);
   var plinth=GameObject.CreatePrimitive(PrimitiveType.Cylinder);plinth.name="Car display";plinth.transform.SetParent(showroom.transform);plinth.transform.position=new Vector3(0,-.1f,0);plinth.transform.localScale=new Vector3(7.3f,.14f,7.3f);plinth.GetComponent<Renderer>().sharedMaterial=ModelLibrary.Material("plinth",new Color(.055f,.075f,.095f));
   for(int i=0;i<60;i++){float a=i*Mathf.PI*2/60;var o=TrackWorld.Cube("Display lights",new Vector3(Mathf.Cos(a)*3.55f,.046f,Mathf.Sin(a)*3.55f),new Vector3(.17f,.025f,.055f),ModelLibrary.Material("displaycyan",new Color(.19f,.87f,.87f),.4f),false);o.transform.rotation=Quaternion.Euler(0,-a*Mathf.Rad2Deg,0);o.transform.SetParent(showroom.transform);}
   for(int i=0;i<16;i++){float a=i*Mathf.PI*2/16;var wall=CarParts.Part(showroom.transform,"Studio wall",PrimitiveType.Cube,new Vector3(Mathf.Sin(a)*16,5,Mathf.Cos(a)*16),new Vector3(6.4f,10,.5f),ModelLibrary.Material("Studio wall",new Color(.027f,.043f,.062f)),new Vector3(0,a*Mathf.Rad2Deg,0));CarParts.Part(showroom.transform,"Studio light strip",PrimitiveType.Cube,new Vector3(Mathf.Sin(a)*15.7f,4,Mathf.Cos(a)*15.7f),new Vector3(.06f,6,.06f),ModelLibrary.Material("Studio strip",new Color(.25f,.58f,.67f),1.1f));}
   for(int i=-1;i<=1;i++)CarParts.Part(showroom.transform,"Softbox",PrimitiveType.Cube,new Vector3(i*4,7,0),new Vector3(2,.06f,9),ModelLibrary.Material("Studio softbox",new Color(.7f,.8f,.86f),1.4f));
   var floorMat=floor.GetComponent<Renderer>().sharedMaterial;floorMat.SetFloat("_Surface",4);floorMat.SetFloat("_Smoothness",.64f);floorMat.SetFloat("_Metallic",.25f);
   Presentation.Lighting(-1);
   for(int i=0;i<3;i++){var light=new GameObject("Studio soft light").AddComponent<Light>();light.transform.SetParent(showroom.transform);light.type=LightType.Point;light.range=17;light.intensity=i==0?1.8f:1.1f;light.color=i==1?new Color(.35f,.75f,1):i==2?new Color(1,.7f,.45f):Color.white;light.transform.position=new Vector3(i==0?-4:4,5,i==2?-4:4);}
   Presentation.Probe(showroom.transform,new Vector3(0,2,0));ShowCar();
  }
  void ShowCar(){if(preview){preview.SetActive(false);Destroy(preview);}preview=ModelLibrary.Create(CarSpec.All[selectedCar].name,showroom.transform);StoreCar();CarParts.Apply(preview,CurrentCar);ApplyInventoryVisual(preview);foreach(var t in preview.GetComponentsInChildren<Transform>())t.gameObject.layer=8;}
  IEnumerator Begin(){
   if(loading)yield break;loading=true;ClearResults();stuntRewardGranted=false;stuntAward=0;Save();yield return null;Destroy(showroom);if(track)Destroy(track.gameObject);foreach(var v in racers)if(v)Destroy(v.gameObject);foreach(var p in boxes)if(p)Destroy(p.gameObject);foreach(var r in FindObjectsByType<Rocket>())Destroy(r.gameObject);racers.Clear();boxes.Clear();finishedCount=0;
   RushReset();track=new GameObject(stuntMode?"Heartstopper":rushMode?Challenge.name:TrackWorld.Names[mapIndex]).AddComponent<TrackWorld>();if(stuntMode)track.GenerateStunts();else if(rushMode)track.GenerateRush(rushIndex);else {track.Generate(mapIndex);RoadGuideLights.Build(track);}track.BuildMapDetails();track.ConnectFeatures(this);ApplyDeviceQuality();cam.farClipPlane=stuntMode?10000:track.IsAirah?6200:3000;
   for(int i=0;i<=(stuntMode?Mathf.Clamp(stuntAiCount,0,9):rushMode?Challenge.opponents:aiCount);i++){int n=stuntMode||rushMode?0:(TrackWorld.Count-2-i/2*2)%TrackWorld.Count;Vector3 p=stuntMode?track.StuntPosition(-i/2*7)+Vector3.right*(i%2==0?-3:3)+Vector3.up*.55f:rushMode?new Vector3((i%2==0?-1:1)*3,5.55f,-12-i/2*7):track.points[n]+track.Right(n)*(i%2==0?-1:1)*(track.map==1?1.65f:3)+Vector3.up*.55f;var v=new GameObject(i==0?"Player":botNames[(i-1)%botNames.Length]).AddComponent<Vehicle>();v.Initialize(this,i==0?selectedCar:(i-1)%CarSpec.All.Length,i==0,i==0?"You":botNames[(i-1)%botNames.Length],p,Quaternion.LookRotation(track.Forward(n)),i==0?engineLevel:0,i==0?tireLevel:0,i==0?brakeLevel:0);racers.Add(v);if(i==0){player=v;CarParts.Apply(v.model,CurrentCar);ApplyInventoryVisual(v.model);if(rushMode){var fill=new GameObject("Rush car fill").AddComponent<Light>();fill.transform.SetParent(v.transform,false);fill.transform.localPosition=new Vector3(0,4,-2);fill.type=LightType.Point;fill.range=13;fill.intensity=.65f;fill.color=new Color(.66f,.77f,1);if(rushIndex==2)PremiumLighting.Headlights(v.transform,true,1);}if(CurrentCar.starTrail&&SupportStore.Owned("star-trail")){var stars=RaceEffects.Emitter(v.transform,"Starlight boost trail",new Color(.7f,.4f,1),.9f,.18f,1,70);stars.transform.localPosition=Vector3.back*2;stars.gameObject.AddComponent<SupportTrail>();}}else CarParts.Apply(v.model,new SavedCar{body=v.carIndex,paint=(i*3+1)%Paints.Length,accent=(i*2+4)%Paints.Length,wheel=i%10,wheelColor=(i+4)%Paints.Length,glass=i%13,engine=i%11});}
   if(powerups||rushMode||stuntMode)foreach(Vector3 p in track.pickups){var o=RaceEffects.Crate();o.transform.position=p;var box=o.AddComponent<Pickup>();box.game=this;box.home=p;boxes.Add(box);}
   BeginDrivingSkills();raceTime=0;countdown=3.8f;state=State.Countdown;cam.transform.position=player.transform.position-player.transform.forward*9+Vector3.up*4;cam.transform.LookAt(player.transform.position+Vector3.up);cameraVel=Vector3.zero;loading=false;
  }
  public void StartRace(){if(loading)return;Time.timeScale=1;state=State.Countdown;StartCoroutine(Begin());}
  void Update(){
   StartupUpdate();UpdatePhoneInput();
   if(messageTimer>0)messageTimer-=Time.unscaledDeltaTime;
   if(!loading&&state==State.Countdown){countdown-=Time.deltaTime;if(countdown<=0){state=State.Race;RushGo();Toast("Go!");}}
   if(!loading&&RaceSimulationActive){raceTime+=Time.deltaTime;UpdateRacePlaces();}UpdateResultsPresentation();
   RushUpdate();if(Input.GetKeyDown(KeyCode.Escape))HandleBack();
   GarageInput();
   cameraShake=Mathf.Max(0,cameraShake-Time.unscaledDeltaTime);
   if(Environment.GetCommandLineArgs().Contains("-aetherTest"))TestDriver();
  }
  void LateUpdate(){
   if(state==State.Menu&&preview){Vector3 offset=Quaternion.Euler(0,orbit,0)*new Vector3(0,menu=="Garage"?viewHeight:2.8f,menu=="Garage"?zoom:8.5f);cam.transform.position=offset;cam.transform.LookAt(new Vector3(0,.55f,0));cam.transform.rotation*=Quaternion.Euler(0,menu=="Play"?-8:menu=="Garage"?5:0,0);cam.fieldOfView=45;}
   else if(player&&stuntMode){UpdateStuntCamera();}
   else if(player){Vector3 forward=player.transform.forward;if(player.body.linearVelocity.magnitude>4)forward=Vector3.Slerp(forward,player.body.linearVelocity.normalized,.22f);forward.y=0;forward.Normalize();Vector3 desired=player.transform.position-forward*8.6f+Vector3.up*3.9f;if(stuntMode)desired+=player.body.linearVelocity*.09f;if(Vector3.Distance(cam.transform.position,desired)>65){cam.transform.position=desired;cameraVel=Vector3.zero;}cam.transform.position=Vector3.SmoothDamp(cam.transform.position,desired,ref cameraVel,.14f,200,Time.unscaledDeltaTime);Vector3 focus=player.transform.position+player.transform.forward*5+Vector3.up*1.05f;cam.transform.rotation=Quaternion.Slerp(cam.transform.rotation,Quaternion.LookRotation(focus-cam.transform.position),Time.unscaledDeltaTime*10);cam.fieldOfView=Mathf.Lerp(cam.fieldOfView,60+Mathf.Clamp01(player.speed/250)*13+(player.boost>0?7:0),Time.unscaledDeltaTime*3);if(cameraShake>0)cam.transform.position+=UnityEngine.Random.insideUnitSphere*cameraShake*.25f;}
   if(player)foreach(var v in racers)if(v!=player)foreach(var r in v.ShadowRenderers)if(r)r.shadowCastingMode=Vector3.Distance(v.transform.position,cam.transform.position)<5?UnityEngine.Rendering.ShadowCastingMode.ShadowsOnly:UnityEngine.Rendering.ShadowCastingMode.On;
  }
  public void Toast(string s){message=s;messageTimer=3;}
  public void OnFinish(Vehicle v){if(v.finishOrder>0)return;v.finishOrder=++finishedCount;UpdateRacePlaces();if(v==player){AwardDrivingSkills();BeginFinishCelebration();}if(stuntMode){AwardStunts(v);return;}if(rushMode){AwardRush(v);return;}if(v.player){int award=500+Mathf.Max(0,aiCount+2-finishedCount)*80+v.coins*10;circuitAward=award;credits+=award;Save();Toast("Finished! +"+award+" credits");}}
  static Material fxMaterial;static AudioClip impactClip;
  public static Material FXMaterial(){if(fxMaterial)return fxMaterial;var tex=new Texture2D(32,32,TextureFormat.RGBA32,false);var colors=new Color[1024];for(int y=0;y<32;y++)for(int x=0;x<32;x++){float a=Mathf.Clamp01(1-new Vector2(x-15.5f,y-15.5f).magnitude/15.5f);colors[y*32+x]=new Color(1,1,1,a*a);}tex.SetPixels(colors);tex.Apply();fxMaterial=new Material(Shader.Find("Sprites/Default"));fxMaterial.mainTexture=tex;return fxMaterial;}
  public void Burst(Vector3 p,Color c,float amount){var o=new GameObject("Impact sparks");o.transform.position=p;var ps=o.AddComponent<ParticleSystem>();var main=ps.main;main.loop=false;main.startLifetime=.35f;main.startSpeed=7*amount;main.startSize=.16f;main.startColor=c;main.gravityModifier=1;var emission=ps.emission;emission.rateOverTime=0;emission.SetBursts(new[]{new ParticleSystem.Burst(0,(short)(24*amount))});var shape=ps.shape;shape.shapeType=ParticleSystemShapeType.Sphere;shape.radius=.2f;ps.GetComponent<ParticleSystemRenderer>().material=FXMaterial();ps.Play();if(player&&Vector3.Distance(p,player.transform.position)<35){if(!impactClip){impactClip=AudioClip.Create("Collision impact",11025,1,44100,false);var samples=new float[11025];var random=new System.Random(42);for(int i=0;i<samples.Length;i++)samples[i]=((float)random.NextDouble()*2-1)*Mathf.Exp(-i/1500f)*.8f;impactClip.SetData(samples,0);}var sound=o.AddComponent<AudioSource>();sound.clip=impactClip;sound.volume=volume*Mathf.Min(.35f,amount*.15f);sound.pitch=.7f+amount*.2f;sound.Play();}Destroy(o,1.5f);}
  public void MainMenu(){ReturnMenu();menu="Play";stuntMode=false;rushMode=false;stuntTab=false;circuitTab=false;}
  void ReturnMenu(){ClearResults();Time.timeScale=1;foreach(var p in boxes)if(p)Destroy(p.gameObject);foreach(var r in FindObjectsByType<Rocket>())Destroy(r.gameObject);foreach(var v in racers)if(v)Destroy(v.gameObject);racers.Clear();if(track)Destroy(track.gameObject);player=null;state=State.Menu;MakeShowroom();}
  void Styles(){if(pixel)return;pixel=Texture2D.whiteTexture;text=new GUIStyle(GUI.skin.label){fontSize=21,normal={textColor=new Color(.89f,.94f,1)},wordWrap=true};small=new GUIStyle(text){fontSize=17};title=new GUIStyle(text){fontSize=50,fontStyle=FontStyle.Bold};button=new GUIStyle(GUI.skin.button){fontSize=21,alignment=TextAnchor.MiddleCenter,normal={background=Texture2D.whiteTexture,textColor=Color.white},hover={background=Texture2D.whiteTexture,textColor=Color.white},active={background=Texture2D.whiteTexture,textColor=Color.white},border=new RectOffset(0,0,0,0)};}
  Color ink=new Color(.045f,.07f,.12f,.96f),cyan=new Color(.27f,.90f,.86f),muted=new Color(.82f,.87f,.92f);
  void Panel(float x,float y,float w,float h,float a=.94f){DrawPanel(new Rect(x,y,w,h),a);}
  void Line(float x,float y,float w,Color c){GUI.color=c;GUI.DrawTexture(new Rect(x,y,w,2),pixel);GUI.color=Color.white;}
  void Label(string s,float x,float y,float w=400,float h=34,int size=21,Color? color=null,bool bold=false){var st=new GUIStyle(text){fontSize=size,fontStyle=bold?FontStyle.Bold:FontStyle.Normal};st.normal.textColor=color??Color.white;GUI.Label(new Rect(x,y,w,h),s,st);}
  bool Button(string s,float x,float y,float w,float h=48,bool primary=false){return CustomButton(s,new Rect(x,y,w,h),primary);}
  void Bar(string label,float value,float max,float x,float y,float width=340,string suffix=""){Label(label,x,y,width,30,18,muted);Label(value.ToString("0")+suffix,x+width-100,y,100,30,18,Color.white);Panel(x,y+31,width,5,1);GUI.color=cyan;GUI.DrawTexture(new Rect(x,y+31,width*Mathf.Clamp01(value/max),5),pixel);GUI.color=Color.white;}
  void OnGUI(){if(CityTest.HideHUD)return;Styles();SetUIMatrix();if(StartupGUI())return;
   if(loading){RushLoadingGUI();return;}
   if(ResultsPresentationGUI())return;if(state==State.Menu)RushMenuGUI();else if(stuntMode)StuntRaceGUI();else if(rushMode)RushRaceGUI();else RaceGUI();DrivingSkillsGUI();if(state==State.Pause&&player)DrivingGoalsPauseGUI();
   if(messageTimer>0){float toastY=phoneMode&&state!=State.Menu?335:797;Panel(550,toastY,500,49,.94f);Label(message,568,toastY+9,468,36,20,cyan);}
  }
  
  void SetupGUI(){
   MapQuirks(655,196,360);Panel(40,196,590,508);Label("Game Setup",65,216,490,50,32,null,true);Label("Choose a circuit",65,276,450,30,20,muted);
   for(int i=0;i<TrackWorld.Names.Length;i++){if(Button(TrackWorld.Names[i],65,312+i*55,535,47,mapIndex==i))mapIndex=i;}
   Label(TrackWorld.Descriptions[mapIndex],65,539,520,65,19,muted);if(mapIndex==1)Label("Map data: OpenStreetMap contributors · ODbL",65,602,540,25,17,muted);if(Button("Play",65,632,535,49,true))StartRace();
   Panel(1040,196,520,508);Label("Race settings",1065,218,450,45,31,null,true);
   Stepper("AI opponents",ref aiCount,0,19,1065,283);Stepper("Laps",ref laps,1,5,1065,348);Stepper("Difficulty",ref difficulty,0,2,1065,413,new[]{"Easy","Normal","Hard"});
   if(Button(powerups?"Power-ups: On":"Power-ups: Off",1065,493,465,48,powerups))powerups=!powerups;
   Label("Leaving the marked circuit starts a 5-second return countdown, including side roads.",1065,570,455,94,19,muted);
  }
  void Stepper(string name,ref int value,int min,int max,float x,float y,string[] names=null){Label(name,x,y+6,230);if(Button("−",x+235,y,48,40))value=Mathf.Max(min,value-1);Label(names==null?value.ToString():names[value],x+294,y+7,110,30,19,cyan);if(Button("+",x+417,y,48,40))value=Mathf.Min(max,value+1);}
  
  
  void ControlsGUI(){if(phoneMode&&Button(mobileFrameRate==120?"Frame rate: Up to 120 FPS":"Frame rate: 60 FPS",1065,728,465,58,true))SetMobileFrameRate(mobileFrameRate==120?60:120);if(Button(phoneMode?"Controls: Phone · Change":"Controls: PC · Change",610,728,470,58,true)){launchScreen=LaunchScreen.DeviceChoice;}Panel(40,196,600,508);Label("Controls",65,219,530,49,32,null,true);string[] lines=phoneMode?new[]{"Left / Right     Steer","Up / Accelerate     Hold to drive","Down / Brake     Brake or reverse","Drift     Hold while steering","Boost     Hold for extra speed","Item button     Use power-up","Reset car     Return to road","Back / Pause     Pause or go back"}:new[]{"W / ↑     Accelerate","S / ↓     Brake · hold to reverse","A D / ← →     Steer","Space     Drift","Left Shift     Boost","E     Use power-up","R     Reset car to road","Esc     Pause / Resume"};for(int i=0;i<lines.Length;i++)Label(lines[i],65,287+i*43,535,35,21,i<4?Color.white:muted);Panel(1040,196,520,508);Label("Power-ups",1065,220,450,45,31,null,true);Label("Boost · extra acceleration\nShield · double mass, forceful impacts\nRocket · heavy homing blast\nPulse · nearby push\nIce Blast · freezes cars for 1.5s\nEMP · disables boost for 3s\nOil Slick · slippery trail\nGravity Mine · pulls, then blasts\nShockwave · wide launching wave",1065,277,448,327,20);Label("Audio volume",1065,613,450,30,20,muted);float old=volume;volume=GUI.HorizontalSlider(new Rect(1065,659,450,25),volume,0,1);if(Mathf.Abs(old-volume)>.01f)Save();}
  void RaceGUI(){
   if(!player)return;if(phoneMode)PhoneRaceHUD();else {Panel(28,25,288,119,.92f);Label(player.place+" / "+racers.Count,48,35,240,59,44,null,true);Label("Lap "+Mathf.Clamp(player.completedLaps+1,1,laps)+" / "+laps,49,99,240,32,21,cyan);
   Panel(636,25,328,71,.9f);Label(TrackWorld.Names[mapIndex],656,35,290,30,22,null,true);Label(TimeFormat(raceTime),656,67,280,26,17,muted);
   Label(player.coins+" coins · "+(player.coins*100)+" points",636,110,430,36,22,cyan,true);MiniMap();Panel(1272,698,300,170,.92f);Label(player.speed.ToString("000"),1294,709,236,81,65,null,true);Label("km/h",1490,757,70,31,18,muted);Bar("Boost",player.energy,100,1294,811,252);
   Panel(28,733,365,135,.93f);Label(player.item==""?"Collect a power-up":player.item+"  [E]",49,751,325,40,25,player.item==""?muted:cyan,true);Label(player.shield>0?"Shield: "+player.shield.ToString("0.0")+"s":"Shift: Boost   ·   Space: Drift",49,810,322,31,18,muted);
   var leaders=racers.OrderBy(v=>v.place).Take(5).ToArray();Panel(28,166,288,184,.84f);for(int i=0;i<leaders.Length;i++)Label(leaders[i].place+"  "+leaders[i].driver,44,179+i*32,259,29,17,leaders[i].player?cyan:Color.white);
   }TrackReturnGUI();
   if(state==State.Countdown){Panel(662,327,276,161,.82f);Label(countdown>1?Mathf.CeilToInt(countdown-1).ToString():"Ready",706,357,230,91,65,cyan,true);}
   if(state==State.Pause){Panel(0,0,1600,900,.65f);Panel(580,223,440,459);Label("Paused",620,256,360,61,42,null,true);if(Button("Resume",620,353,360,54,true)){state=beforePause;Time.timeScale=1;}if(Button("Restart",620,429,360,54)){StartRace();}if(Button("Game Setup",620,505,360,54)){ReturnMenu();menu="Game Setup";}if(Button("Main Menu",620,581,360,54)){ReturnMenu();menu="Play";}}
   if(state==State.Results){Panel(0,0,1600,900,.75f);Panel(414,115,772,650);Label("Match Results",450,146,700,62,43,null,true);Label(TrackWorld.Names[mapIndex]+" · "+laps+(laps==1?" lap":" laps"),451,212,685,37,22,cyan);Label(player.coins+" coins · "+player.coins*100+" points · +"+player.coins*10+" coin credits",451,244,680,30,18,cyan);var order=racers.OrderBy(v=>v.place).Take(20).ToArray();for(int i=0;i<order.Length;i++){var v=order[i];Label(v.place+"   "+v.driver,453+(i/10)*349,283+(i%10)*31,245,29,18,v.player?cyan:Color.white);Label(v.finished?TimeFormat(v.finishTime):"Not finished",699+(i/10)*349,283+(i%10)*31,104,29,16,muted);}if(Button("Restart",451,662,215,57,true))StartRace();if(Button("Game Setup",681,662,215,57)){ReturnMenu();menu="Game Setup";}if(Button("Main Menu",911,662,235,57))MainMenu();}
  }
  string TimeFormat(float t)=>((int)t/60).ToString("00")+":"+(t%60).ToString("00.00");
  void MiniMap(){Rect r=new Rect(1328,25,244,244);Panel(r.x,r.y,r.width,r.height,.87f);Label("Circuit",1345,36,200,27,17,muted);float mapScale=track.IsAirah?.079f:.25f;Vector2 P(Vector3 p)=>new Vector2(r.x+122+p.x*mapScale,r.y+137-p.z*mapScale);for(int i=0;i<TrackWorld.Count;i+=2){Vector2 p=P(track.points[i]);GUI.color=new Color(.39f,.52f,.64f);GUI.DrawTexture(new Rect(p.x-2,p.y-2,4,4),pixel);}foreach(var v in racers){Vector2 p=P(v.transform.position);GUI.color=v.player?cyan:new Color(1,.50f,.35f);GUI.DrawTexture(new Rect(p.x-4,p.y-4,8,8),pixel);}GUI.color=Color.white;}
  // Optional reproducible smoke test; logs assertions and captures actual rendered frames.
  void TestDriver(){
   testTimer+=Time.unscaledDeltaTime;
   if(testStage==0&&testTimer>4){ScreenCapture.CaptureScreenshot(evidencePath+"/menu.png");testStage++;testTimer=0;}
   else if(testStage==1&&testTimer>1){menu="Garage";ScreenCapture.CaptureScreenshot(evidencePath+"/garage.png");testStage=10;testTimer=0;}
   else if(testStage==10&&testTimer>1){laps=1;StartRace();testStage=2;testTimer=0;}
   else if(testStage==2&&state==State.Race){player.player=false;testStage++;testTimer=0;Debug.Log("AETHER_TEST Race started. cars="+racers.Count+" trackMeters="+track.length);}
   else if(testStage==3&&testTimer>18){ScreenCapture.CaptureScreenshot(evidencePath+"/race-"+mapIndex+".png");Debug.Log("AETHER_TEST after18s speed="+player.speed+" progress="+player.progress+" grounded="+player.grounded+" position="+player.transform.position);player.item="Shield";player.UseItem();Debug.Assert(player.shield>0,"Shield failed");player.item="Boost";player.UseItem();Debug.Assert(player.boost>0,"Boost failed");testStage++;testTimer=0;}
   else if(testStage==4){testFps+=Time.unscaledDeltaTime;testFrames++;if(state==State.Results||testTimer>240){Debug.Log("AETHER_TEST map="+mapIndex+" state="+state+" fps="+(testFrames/testFps)+" "+string.Join("; ",racers.Select(v=>v.driver+" progress="+v.progress.ToString("F1")+" gate="+v.circuitCheckpoint+" finished="+v.finished+" speed="+v.speed.ToString("F1"))));Debug.Assert(state==State.Results,"Race did not finish");ScreenCapture.CaptureScreenshot(evidencePath+"/results-"+mapIndex+".png");testStage++;testTimer=0;}}
   else if(testStage==5&&testTimer>1){if(mapIndex<2){mapIndex++;StartRace();testStage=2;testTimer=0;testFps=0;testFrames=0;}else Application.Quit();}
  }
 }
 public class Pickup:MonoBehaviour {
  public static string ChooseItem(Game game,Vehicle receiver,float roll){bool rival=game.racers.Exists(v=>v&&v!=receiver&&!v.finished);string[] pool=rival?(game.rushMode?RushWeapons:WeaponCatalog.Items):SoloWeapons;return pool[Mathf.Clamp(Mathf.FloorToInt(Mathf.Clamp01(roll)*pool.Length),0,pool.Length-1)];}
  static readonly string[] SoloWeapons={"Boost","Shield"};
  public static readonly string[] RushWeapons={"Rocket","Rocket","Ice Blast","EMP","Oil Slick","Gravity Mine","Shockwave","Pulse","Boost","Shield"};
  public Game game;public Vector3 home;float cooldown;Renderer[] visuals;public bool Available=>cooldown<=0;
  void Start(){visuals=GetComponentsInChildren<Renderer>();}
  void Update(){if(!game.RaceSimulationActive&&game.state!=Game.State.Countdown)return;transform.rotation=Quaternion.Euler(0,Time.time*42,Mathf.Sin(Time.time)*5);transform.position=home+Vector3.up*Mathf.Sin(Time.time*2+home.x)*.2f;
   if(cooldown>0)cooldown-=Time.deltaTime;bool visible=cooldown<=0;foreach(var r in visuals)if(r)r.enabled=visible;if(!visible)return;
   foreach(var v in game.racers)if(!v.finished&&v.item==""&&Vector3.Distance(v.transform.position+Vector3.up,home)<2.7f){v.item=ChooseItem(game,v,UnityEngine.Random.value);cooldown=7;RaceEffects.Debris(home,new Color(.4f,.27f,.12f),10,5);RaceEffects.Burst(home,new Color(.16f,1,.72f),24,5,.2f,.65f);RaceEffects.Ring(home,new Color(.16f,1,.72f),3);foreach(var r in visuals)if(r)r.enabled=false;if(v.player)game.Toast(v.item+(game.phoneMode?" collected · tap Item":" collected · press E"));break;}
  }
 }
}
