using System;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEngine;
namespace Aether {
 public class PremiumTest:MonoBehaviour {
  Game game;int failures;float watchdog;string output;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){if(Environment.GetCommandLineArgs().Contains("-aetherPremiumTest"))new GameObject("Premium verification").AddComponent<PremiumTest>();}
  void Check(bool value,string name){Debug.Log("PREMIUM "+(value?"PASS ":"FAIL ")+name);if(!value)failures++;}
  void Update(){watchdog+=Time.unscaledDeltaTime;if(watchdog>210){Debug.LogError("PREMIUM TIMEOUT");Application.Quit(2);}}
  IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return null;}
  void Place(Vehicle car,int n,float lane=0){Vector3 p=game.track.points[n]+game.track.Right(n)*lane+Vector3.up*.6f;Quaternion q=Quaternion.LookRotation(game.track.Forward(n));car.body.linearVelocity=car.body.angularVelocity=Vector3.zero;car.transform.SetPositionAndRotation(p,q);car.body.position=p;car.body.rotation=q;car.lastPoint=n;car.offTrackTime=car.wrongWayTime=car.trappedTime=0;Physics.SyncTransforms();}

  IEnumerator Start(){
   output=Path.GetFullPath(Application.dataPath+"/../../Evidence/Premium");Directory.CreateDirectory(output);yield return new WaitForSeconds(1);game=FindAnyObjectByType<Game>();game.ChooseDevice(false);game.menu="Support";yield return Shot("01-support");game.menu="Game Setup";game.mapIndex=1;yield return Shot("02-map-details");
   Check(WeaponCatalog.Items.Length==9&&WeaponCatalog.Items.Distinct().Count()==9,"Nine distinct pickable items");
   Check(!SupportStore.Verify("invalid.code","test",out var sku),"Invalid purchase code rejected");
   Check(SupportStore.Checkout(SupportStore.Products[3],"test-player").Contains("amount=9.99&currency_code=USD")&&SupportStore.Checkout(SupportStore.Products[0],"test-player").Contains("business=lemonquake%40gmail.com"),"PayPal recipient, currency and product price encoded");
   game.mapIndex=0;game.aiCount=1;game.StartRace();yield return new WaitUntil(()=>game.state==Game.State.Race);var car=game.player;var other=game.racers[1];car.manualTest=other.manualTest=true;car.body.interpolation=other.body.interpolation=RigidbodyInterpolation.None;car.enforceTrackBounds=other.enforceTrackBounds=false;car.throttle=other.throttle=0;
   var traffic=game.track.GetComponentsInChildren<TricycleTraffic>();Check(traffic.Length==60&&traffic.Count(t=>t.travelSign<0)==48,"60 circuit vehicles, 48 oncoming");Check(traffic.Count(t=>t.name.Contains("jeepney"))==20,"20 moving jeepneys");var initial=traffic.Select(t=>t.transform.position).ToArray();yield return new WaitForSeconds(2);Check(traffic.Where((t,i)=>Vector3.Distance(t.transform.position,initial[i])>1).Count()>35,"Most circuit traffic actively driving");
   Check(traffic.Where(t=>t.name.StartsWith("Circuit civilian")).All(t=>{var tail=t.GetComponentsInChildren<MeshRenderer>().FirstOrDefault(r=>r.sharedMaterial.name=="Kenney_d3363d");return tail&&t.transform.InverseTransformPoint(tail.bounds.center).z<0;}),"Civilian rear lamps are behind the forward driving axis");Check(traffic.Count(t=>t.travelSign<0&&Vector3.Dot(t.GetComponent<Rigidbody>().linearVelocity,t.transform.forward)>1)>30,"Oncoming traffic drives nose-first against the race direction");
   Place(car,5);Place(other,6);other.Freeze();Check(other.frozenFor==1.5f,"Ice starts a 1.5-second hold");yield return new WaitForSeconds(.35f);Check(other.transform.Find("Ice enclosure")&&other.speed<1,"Animated ice encloses and immobilizes car");yield return Shot("03-ice-blast");game.PauseRace();float frozen=other.frozenFor;yield return new WaitForSecondsRealtime(.25f);Check(Mathf.Abs(other.frozenFor-frozen)<.01f,"Pause freezes weapon timer");game.HandleBack();yield return new WaitForSeconds(1.2f);Check(other.frozenFor==0&&!other.transform.Find("Ice enclosure"),"Ice shatters and releases after 1.5 seconds");
   Place(car,5);Place(other,6);car.item="EMP";car.UseItem();Check(other.empFor>2.9f&&other.energy<=10,"EMP disables nearby boost");other.ClearWeaponStatus();other.shield=8;other.Freeze();Check(other.frozenFor==0&&other.shield==0,"Shield blocks Ice Blast");
   foreach(string weapon in new[]{"Oil Slick","Gravity Mine","Shockwave"}){car.item=weapon;car.UseItem();Check(car.item=="","Consumed "+weapon);}Check(game.track.GetComponentsInChildren<WeaponHazard>().Length==2,"Oil and gravity hazards remain on the road");
   var hazards=game.track.GetComponentsInChildren<WeaponHazard>();var oil=hazards.First(h=>h.name=="Oil Slick");Place(other,5);other.body.constraints=RigidbodyConstraints.FreezeAll;other.transform.position=oil.transform.position+Vector3.up*.6f;other.body.position=other.transform.position;Physics.SyncTransforms();yield return new WaitForSeconds(.75f);Check(other.oilFor>0,"Oil slick reduces grip on contact");yield return new WaitForSeconds(1);Check(!game.track.GetComponentsInChildren<WeaponHazard>().Any(h=>h.name=="Gravity Mine"),"Gravity mine arms and detonates near opponent");
   other.body.constraints=RigidbodyConstraints.None;Place(other,8);var rocket=RaceEffects.Missile().AddComponent<Rocket>();rocket.game=game;rocket.owner=car;rocket.transform.position=other.transform.position+Vector3.right;rocket.Explode();yield return new WaitForFixedUpdate();Check(other.body.linearVelocity.magnitude>22,"Missile produces a strong blast impulse");
   var lamp=game.track.GetComponentsInChildren<RespawningStreetLamp>()[0];var home=lamp.transform.position;lamp.GetComponent<CityProp>().Break(home,Vector3.right*18);yield return new WaitForSeconds(9);Check(lamp.respawns==0&&lamp.remaining>.5f,"Streetlamp waits ten seconds");game.PauseRace();float remaining=lamp.remaining;yield return new WaitForSecondsRealtime(.3f);Check(Mathf.Abs(lamp.remaining-remaining)<.01f,"Lamp respawn pauses with race");game.HandleBack();yield return new WaitForSeconds(1.3f);Check(lamp.respawns==1&&Vector3.Distance(lamp.transform.position,home)<.1f&&!lamp.GetComponent<CityProp>().broken,"Streetlamp restored at ten seconds");
   Vector3 sideRoad=new Vector3(-230,3.7f,-190);Check(game.track.CityStreet(sideRoad)&&!game.track.InRaceCorridor(sideRoad),"Unrelated paved road lies outside race corridor");car.enforceTrackBounds=true;car.body.constraints=RigidbodyConstraints.FreezeAll;car.transform.position=sideRoad;car.body.position=sideRoad;car.offTrackTime=car.wrongWayTime=car.trappedTime=0;Physics.SyncTransforms();int returns=car.automaticReturns;
   yield return new WaitForSeconds(3.2f);Debug.Log("PREMIUM TIMER elapsed="+car.offTrackTime+" returns="+car.automaticReturns+" baseline="+returns+" pos="+car.transform.position);Check(car.offTrackTime>3&&car.automaticReturns==returns,"Off-route paved road starts five-second countdown");Place(car,5);yield return null;Check(car.offTrackTime==0,"Rejoining circuit cancels countdown");car.transform.position=sideRoad;car.body.position=sideRoad;Physics.SyncTransforms();yield return new WaitForSeconds(5.3f);Check(car.automaticReturns==returns+1&&game.track.InRaceCorridor(car.transform.position),"Off-route paved road returns car at five seconds");car.body.constraints=RigidbodyConstraints.None;
   Place(car,5);yield return Shot("04-downtown");game.mapIndex=1;game.aiCount=19;game.StartRace();yield return new WaitUntil(()=>game.state==Game.State.Race);car=game.player;car.manualTest=true;car.throttle=0;Check(GameObject.Find("Sun").GetComponent<Light>().intensity==0,"Malasugue has no sunlight");Check(car.GetComponentsInChildren<Light>().Length==2,"Player has two working headlights");Check(game.track.GetComponentsInChildren<RespawningStreetLamp>().Length>=60,"Night village lined with respawning streetlights");Check(game.track.GetComponentsInChildren<TricycleTraffic>().Length==26,"Town keeps its 26 tricycles");yield return new WaitForSeconds(2);yield return Shot("05-malasugue-night");Place(car,65);yield return new WaitForSeconds(1);yield return Shot("05b-night-driving");
   float began=Time.realtimeSinceStartup;int frames=0;while(Time.realtimeSinceStartup-began<6){frames++;yield return null;}Debug.Log("PREMIUM NIGHT FPS "+(frames/(Time.realtimeSinceStartup-began)).ToString("F1"));
   game.mapIndex=2;game.aiCount=0;game.StartRace();yield return new WaitUntil(()=>game.state==Game.State.Race);Check(game.track.map==2&&GameObject.Find("Sun").GetComponent<Light>().intensity>0,"Garden lighting restored after night village");yield return Shot("06-gardens");
   File.WriteAllText(Path.Combine(output,"test-result.txt"),"failures="+failures);Debug.Log("PREMIUM COMPLETE failures="+failures);Application.Quit(failures==0?0:1);
  }
 }
}
