using System;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEngine;
namespace Aether {
 public class RushTest:MonoBehaviour {
  Game game;int failures;float watchdog;string output;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){if(Environment.GetCommandLineArgs().Contains("-aetherRushTest"))new GameObject("Rush verification").AddComponent<RushTest>();}
  void Check(bool ok,string name){Debug.Log("RUSH "+(ok?"PASS ":"FAIL ")+name);if(!ok)failures++;}
  void Update(){watchdog+=Time.unscaledDeltaTime;if(watchdog>480){Debug.LogError("RUSH TIMEOUT");File.WriteAllText(Path.Combine(output,"test-result.txt"),"TIMEOUT failures="+failures);Application.Quit(2);}}
  IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return null;}
  void Place(Vehicle v,int n,float lane=0){v.body.linearVelocity=v.body.angularVelocity=Vector3.zero;var p=game.track.points[n]+new Vector3(lane,.15f,0);v.body.position=p;v.transform.position=p;v.body.rotation=v.transform.rotation=Quaternion.identity;v.lastPoint=n;v.offTrackTime=v.wrongWayTime=v.trappedTime=0;Physics.SyncTransforms();}
  IEnumerator Start(){output=Path.GetFullPath(Application.dataPath+"/../../Evidence/Rush");Directory.CreateDirectory(output);yield return new WaitForSeconds(1);game=FindAnyObjectByType<Game>();game.ChooseDevice(false);game.inventory=RushSave.Fresh();Check(game.menu=="Play"&&!game.rushMode,"First menu is Play with Rush first, circuit state remains independent");yield return Shot("01-rush-menu");game.menu="Inventory";yield return Shot("02-inventory");
   var s=RushSave.Fresh();Check(!s.Spend("rocket-pack",3)&&s.Count("rocket-pack")==2,"Insufficient items cannot be spent");s.Add("sun-turbo",1);s.engine="sun-turbo";s.records[0].finishes=3;var loaded=JsonUtility.FromJson<RushSave>(JsonUtility.ToJson(s));loaded.Validate();Check(loaded.Count("sun-turbo")==1&&loaded.engine=="sun-turbo"&&loaded.records[0].finishes==3,"Inventory, loadout and map records survive serialization");loaded.engine="missing";loaded.prepared="sun-turbo";loaded.items.Add(new InventoryStack{id="bad",count=99});loaded.Validate();Check(loaded.engine==""&&loaded.prepared==""&&loaded.Count("bad")==0,"Invalid saved loadout and unknown items rejected");
   Check(!game.EquipInventory("sun-turbo"),"Unowned equipment cannot be equipped");game.inventory.Add("sun-turbo",1);game.inventory.Add("storm-coil",1);game.EquipInventory("sun-turbo");game.EquipInventory("storm-coil");Check(game.inventory.engine=="storm-coil","Engine attachments replace one another");game.inventory.Add("upgrade-part",3);int level=game.CurrentCar.engineLevel;Check(game.UpgradeWithParts(0)&&game.CurrentCar.engineLevel==level+1&&game.inventory.Count("upgrade-part")==0,"Parts buy one real car upgrade");Check(!game.UpgradeWithParts(0),"Upgrade cannot spend absent parts");game.inventory.prepared="rocket-pack";
   for(int map=0;map<3;map++){
    Debug.Log("RUSH START MAP "+map);game.StartRush(map);yield return new WaitUntil(()=>game.state==Game.State.Race);var t=game.track;var car=game.player;Check(t.isRush&&t.points.All(p=>Mathf.Abs(p.x)<.001f)&&Mathf.Abs(t.points.Last().z-RushMap.All[map].meters)<.1f,"Map "+map+" is a full-length straight road");Check(Vector3.Dot(t.Forward(0),Vector3.forward)>.99f&&Vector3.Dot(t.Forward(479),Vector3.forward)>.99f,"Endpoint headings never loop back");Check(Physics.Raycast(new Vector3(0,9,320),Vector3.down,out var hit,10)&&hit.point.y>4.9f,"Combined road retains colliders");car.rushSafePoint=0;var originalPosition=car.transform.position;car.transform.position=new Vector3(30,5,800);t.SafeReturnPose(car,game,out var safePosition,out var safeRotation,out var safePoint);Check(safePoint==0&&safePosition.z<1,"Off-road recovery cannot skip forward");car.transform.position=originalPosition;Physics.SyncTransforms();Check(t.tiles.Count>25&&t.pickups.Count>30&&t.rushHazards.Count>10,"Map contains ramps, boosts, crates and traps");Check(game.racers.Count==RushMap.All[map].opponents+1,"Map rival count");if(map==0)Check(game.inventory.Count("rocket-pack")==1&&car.item=="Rocket","Prepared item consumed once at Go");
    car.manualTest=true;car.throttle=1;car.steer=0;yield return new WaitForSeconds(4);Check(car.speed>35&&car.transform.position.z>0&&car.grounded>=2,"Map "+map+" accelerates and stays on road");yield return Shot("03-race-"+map);
    var traffic=t.GetComponent<RushTrafficSystem>().GetComponentsInChildren<Rigidbody>();var pos=traffic.Select(b=>b.position).ToArray();yield return new WaitForSeconds(.5f);Check(traffic.Where((b,i)=>Vector3.Distance(b.position,pos[i])>2).Count()>=12,"Traffic moves on map "+map);
    var hazard=t.rushHazards[0];Place(car,t.Nearest(hazard.transform.position),hazard.transform.position.x);car.throttle=0;car.body.constraints=RigidbodyConstraints.FreezeAll;hazard.phase=4-game.raceTime;car.shield=0;yield return new WaitForSeconds(.15f);if(map==0)Check(car.oilFor>0,"Coastal oil reduces grip");if(map==1)Check(t.GetComponentsInChildren<Rigidbody>().Any(b=>b.name=="Falling canyon boulder"),"Canyon warning spawns physical falling rock");if(map==2)Check(car.empFor>0,"Electric lanes interrupt boost");
    game.PauseRace();float time=game.raceTime;yield return new WaitForSecondsRealtime(.3f);Check(Mathf.Abs(time-game.raceTime)<.001f,"Pause freezes Rush clock");yield return Shot("04-pause-"+map);game.HandleBack();car.ClearWeaponStatus();car.body.constraints=RigidbodyConstraints.None;
    Place(car,478);car.progress=478;car.throttle=1;car.body.linearVelocity=Vector3.forward*50;float wait=Time.realtimeSinceStartup;while(!car.finished&&Time.realtimeSinceStartup-wait<8)yield return null;Check(car.finished,"Map "+map+" crosses point-to-point finish");if(car.finished){Check(game.inventory.records[map].finishes==1&&game.inventory.Count(RushMap.All[map].prize)>0,"Map signature reward saved");int credits=game.credits,parts=game.inventory.Count("upgrade-part");game.AwardRush(car);Check(game.credits==credits&&game.inventory.Count("upgrade-part")==parts,"Duplicate finish cannot duplicate rewards");yield return new WaitForSecondsRealtime(3);yield return Shot("05-results-"+map);}
   }
   game.StartRush(0);yield return new WaitUntil(()=>game.state==Game.State.Race);game.player.manualTest=true;int before=game.credits,finishes=game.inventory.records[0].finishes;game.raceTime=game.Challenge.seconds;yield return null;Check(game.rushFailed&&game.state==Game.State.Results&&game.credits==before&&game.inventory.records[0].finishes==finishes,"Timeout ends challenge without reward");yield return Shot("06-timeout");game.HandleBack();game.menu="Inventory";yield return Shot("07-earned-inventory");game.ChooseDevice(true);game.StartRush(2);yield return new WaitUntil(()=>game.state==Game.State.Race);game.player.manualTest=true;yield return Shot("08-phone-rush");game.PauseRace();game.HandleBack();game.ChooseDevice(false);
   // One complete autonomous drive uses the same steering, physics, traps and recovery as real rivals.
   game.StartRush(0);yield return new WaitUntil(()=>game.state==Game.State.Race);game.player.player=false;Time.timeScale=3;float began=Time.realtimeSinceStartup;while(game.state==Game.State.Race&&Time.realtimeSinceStartup-began<150)yield return null;Time.timeScale=1;Debug.Log("RUSH DRIVE z="+game.player.transform.position.z+" progress="+game.player.progress+" time="+game.raceTime+" returns="+game.player.automaticReturns);Check(game.player.finished,"Full six-kilometre autonomous race finishes within limit");yield return Shot("09-full-drive");
   game.HandleBack();game.rushMode=false;game.mapIndex=2;game.aiCount=0;game.StartRace();yield return new WaitUntil(()=>game.state==Game.State.Race);Check(!game.track.isRush&&game.track.map==2&&game.track.length>1000,"Existing circuit generation still works");
   File.WriteAllText(Path.Combine(output,"test-result.txt"),"failures="+failures);Debug.Log("RUSH COMPLETE failures="+failures);Application.Quit(failures==0?0:1);
  }
 }
}
