using System.Collections.Generic;
using UnityEngine;
namespace Aether {
 public partial class TrackWorld {
  public bool isRush;public int rushTheme;public float RushEnd=>length;public readonly List<RushHazard> rushHazards=new List<RushHazard>();
  public void GenerateRush(int theme){
   isRush=true;rushTheme=theme;map=theme==2?2:0;length=RushMap.All[theme].meters;rng=new System.Random(1800+theme);
   decor=new GameObject("Rush scenery").transform;decor.SetParent(transform);glow=RushMap.All[theme].color;
   for(int i=0;i<Count;i++)points[i]=new Vector3(0,5,i*length/(Count-1));
   var asphalt=ModelLibrary.Material("Rush asphalt "+theme,new Color(.22f,.25f,.28f));asphalt.SetFloat("_Surface",1);asphalt.SetFloat("_Smoothness",theme==2?.52f:.19f);
   var sand=ModelLibrary.Material("Rush shore "+theme,theme==1?new Color(.48f,.23f,.11f):new Color(.65f,.51f,.32f));sand.SetFloat("_Surface",2);sand.SetFloat("_Smoothness",.08f);
   asphalt.SetTexture("_MainTex",Resources.Load<Texture2D>("Textures/DowntownAsphalt"));asphalt.SetFloat("_TextureMix",.35f);asphalt.SetFloat("_TextureScale",.15f);
   var rail=ModelLibrary.Material("Rush rail",new Color(.25f,.31f,.34f));var stripe=ModelLibrary.Material("Rush white",new Color(.88f,.84f,.7f));var edge=ModelLibrary.Material("Rush edge "+theme,glow,.55f);
   var sea=new Material(Shader.Find("Aether/RushOcean"));sea.SetFloat("_Storm",theme==2?1:0);sea.SetColor("_Color",theme==2?new Color(.025f,.12f,.24f,.95f):new Color(.015f,.32f,.36f,.95f));
   MeshObject("Rush ocean",new[]{new Vector3(-2600,0,-1200),new Vector3(-2600,0,length+2600),new Vector3(3600,0,-1200),new Vector3(3600,0,length+2600)},new[]{0,1,2,2,1,3},sea,false,transform);
   for(int chunk=0;chunk<Mathf.CeilToInt((length+300)/120);chunk++){
    float z=chunk*120-100;var sector=new GameObject("Road sector "+chunk).transform;sector.SetParent(transform);
    var road=Cube("Straight road",new Vector3(0,4.8f,z+60),new Vector3(24,.4f,120.1f),asphalt,true);road.transform.SetParent(sector);
    if(theme!=2){var shore=Cube("Sand verge",new Vector3(-65,1.7f,z+60),new Vector3(170,3,120.1f),sand,true);shore.transform.SetParent(sector);}
    for(int s=-1;s<=1;s+=2){var r=Cube("Road guardrail",new Vector3(s*12.5f,5.65f,z+60),new Vector3(.45f,1.1f,120),rail,true);r.transform.SetParent(sector);CarParts.Part(sector,"Luminous edge",PrimitiveType.Cube,new Vector3(s*12.22f,6.23f,z+60),new Vector3(.14f,.10f,120),edge);}
    for(int j=0;j<10;j++)for(int lane=-1;lane<=1;lane++)CarParts.Part(sector,"Lane dash",PrimitiveType.Cube,new Vector3(lane*6,5.015f,z+j*12+4),new Vector3(.16f,.02f,5),stripe);
    CombineRushSector(sector);
    if(theme==0){for(int j=0;j<3;j++){var palm=ModelLibrary.Create(j%2==0?"K_tree_palmDetailedTall":"K_tree_palmBend",sector);palm.transform.position=new Vector3(-22-j*12,3.2f,z+j*38);palm.transform.localScale=Vector3.one*R(9f,14f);palm.transform.rotation=Quaternion.Euler(0,R(0,360),0);}RushBeach(sector,z);if(chunk%5==0)RushIsland(sector,new Vector3(260+R(0,180),-6,z+140),R(70,110),R(100,160),R(55,105),chunk,false);}
    if(theme==1){for(int s=-1;s<=1;s+=2){RushIsland(sector,new Vector3(s*R(130,185),-9,z+60),R(70,110),R(85,145),R(95,175),chunk+s*43,true);}}
    if(theme==2&&chunk%3==0){for(int s=-1;s<=1;s+=2){CarParts.Part(sector,"Bridge tower",PrimitiveType.Cube,new Vector3(s*16,27,z+40),new Vector3(3,54,4),rail);CarParts.Part(sector,"Tower light",PrimitiveType.Cube,new Vector3(s*14.4f,27,z+37.8f),new Vector3(.25f,42,.1f),edge);for(int k=0;k<8;k++){float zz=z+40+k*40;float yy=11+35*Mathf.Pow((k-4)/4f,2);var a=new Vector3(s*16,yy,zz);var b=new Vector3(s*16,6,zz);CarParts.Part(sector,"Suspension hanger",PrimitiveType.Cube,(a+b)*.5f,new Vector3(.14f,yy-6,.14f),rail);if(k>0){float pz=zz-40,py=11+35*Mathf.Pow((k-5)/4f,2);var from=new Vector3(s*16,py,pz);var cable=Cube("Bridge cable",(from+a)*.5f,new Vector3(.22f,.22f,Vector3.Distance(from,a)),edge,false);cable.transform.rotation=Quaternion.LookRotation(a-from);cable.transform.SetParent(sector);}}}CarParts.Part(sector,"Bridge crossbeam",PrimitiveType.Cube,new Vector3(0,48,z+40),new Vector3(35,3,3),rail);}
   }
   for(int n=18;n<Count-16;n+=17){int lane=(n/17)%3-1;AddTile(n,TileKind.Booster);tiles[tiles.Count-1].transform.position+=Vector3.right*lane*6;}
   for(int n=32;n<Count-15;n+=47){AddRamp(n);var lip=tiles[tiles.Count-1];lip.transform.parent.position+=Vector3.right*((n/47)%2==0?-5:5);}
   for(int n=22;n<Count-12;n+=11){float lane=(n/11%3-1)*6;pickups.Add(points[n]+Vector3.right*lane+Vector3.up*1.4f);}
   for(int n=25;n<Count-12;n+=8){var o=new GameObject("Rush coin");o.transform.SetParent(transform);o.transform.position=points[n]+Vector3.right*((n/8%3-1)*6)+Vector3.up*1.1f;var coin=o.AddComponent<CoinPickup>();coin.home=o.transform.position;coins.Add(coin);CarParts.Part(o.transform,"Coin",PrimitiveType.Cylinder,Vector3.zero,new Vector3(.9f,.09f,.9f),ModelLibrary.Material("Rush gold",new Color(1,.65f,.12f),.5f),new Vector3(90,0,0));}
   for(int n=45;n<Count-10;n+=theme==0?32:21){var o=new GameObject(theme==0?"Oil lane":theme==1?"Falling rock zone":"Electric lane");o.transform.SetParent(transform);o.transform.position=points[n]+Vector3.right*((n/21%3-1)*6);var hazard=o.AddComponent<RushHazard>();hazard.track=this;hazard.kind=theme;hazard.phase=n*.3f;rushHazards.Add(hazard);hazard.Build();}
   for(int n=60;n<Count-18;n+=theme==1?27:49){float x=(n%2==0?-6:6);var o=Cube("Striped roadblock",points[n]+new Vector3(x,.55f,0),new Vector3(3.8f,1.1f,1.4f),ModelLibrary.Material("Hazard charcoal",new Color(.09f,.1f,.12f)),true);o.transform.SetParent(transform);for(int k=0;k<4;k++)CarParts.Part(o.transform,"Warning stripe",PrimitiveType.Cube,new Vector3(-.38f+k*.25f,0,-.51f),new Vector3(.1f,.95f,.025f),edge,new Vector3(0,0,-24));}
   for(int n=0;n<=3;n++)RushGate(n==0?0:n==3?length:length*n/3,n==0?"Start":n==3?"Finish":(n*33)+"%",edge);
   var life=gameObject.AddComponent<RushTrafficSystem>();life.track=this;if(theme==2)gameObject.AddComponent<RushWeather>();
   Presentation.Lighting(theme==2?2:0);var sun=GameObject.Find("Sun").GetComponent<Light>();sun.transform.rotation=Quaternion.Euler(theme==2?24:7,-148,0);sun.color=theme==2?new Color(.5f,.65f,1):new Color(1,.55f,.26f);sun.intensity=theme==2?.8f:1.25f;
   RenderSettings.ambientSkyColor=theme==2?new Color(.17f,.22f,.4f):new Color(.32f,.4f,.5f);RenderSettings.ambientEquatorColor=theme==2?new Color(.12f,.18f,.27f):new Color(.4f,.28f,.23f);
   RenderSettings.fog=true;RenderSettings.fogMode=FogMode.ExponentialSquared;RenderSettings.fogDensity=theme==2?.00065f:.0004f;RenderSettings.fogColor=theme==2?new Color(.13f,.18f,.3f):new Color(.68f,.4f,.28f);
   var sky=new Material(Shader.Find("Aether/RushSky"));sky.SetColor("_Top",theme==2?new Color(.018f,.035f,.12f):new Color(.14f,.22f,.38f));sky.SetColor("_Horizon",theme==2?new Color(.21f,.2f,.4f):new Color(1,.49f,.22f));sky.SetFloat("_Storm",theme==2?1:0);RenderSettings.skybox=sky;DynamicGI.UpdateEnvironment();Presentation.Probe(transform,new Vector3(0,10,60));
  }
  void CombineRushSector(Transform root){var groups=new Dictionary<Material,List<CombineInstance>>();foreach(var mf in root.GetComponentsInChildren<MeshFilter>()){var r=mf.GetComponent<MeshRenderer>();if(!r)continue;var m=r.sharedMaterial;if(!groups.ContainsKey(m))groups[m]=new List<CombineInstance>();groups[m].Add(new CombineInstance{mesh=mf.sharedMesh,transform=root.worldToLocalMatrix*mf.transform.localToWorldMatrix});r.enabled=false;}foreach(var group in groups){var mesh=new Mesh{indexFormat=UnityEngine.Rendering.IndexFormat.UInt32};mesh.CombineMeshes(group.Value.ToArray());var o=new GameObject("Sector mesh");o.transform.SetParent(root,false);o.AddComponent<MeshFilter>().sharedMesh=mesh;o.AddComponent<MeshRenderer>().sharedMaterial=group.Key;o.AddComponent<OwnedMesh>();}}
  void RushGate(float z,string label,Material light){var root=new GameObject(label+" gate").transform;root.SetParent(transform);root.position=new Vector3(0,5,z);var dark=ModelLibrary.Material("Rush gate",new Color(.05f,.075f,.095f));for(int s=-1;s<=1;s+=2){CarParts.Part(root,"Gate column",PrimitiveType.Cube,new Vector3(s*11,4,0),new Vector3(1.2f,8,1.2f),dark);CarParts.Part(root,"Gate strip",PrimitiveType.Cube,new Vector3(s*11,4,-.65f),new Vector3(.3f,7,.08f),light);}CarParts.Part(root,"Gate crossbar",PrimitiveType.Cube,new Vector3(0,8,0),new Vector3(23,1.6f,1.3f),dark);var t=new GameObject("Gate label").AddComponent<TextMesh>();t.transform.SetParent(root,false);t.transform.localPosition=new Vector3(0,8,-.7f);t.text=label;t.fontSize=72;t.characterSize=.35f;t.anchor=TextAnchor.MiddleCenter;t.color=Color.white;for(int x=0;x<12;x++)for(int row=0;row<2;row++)CarParts.Part(root,"Finish checker",PrimitiveType.Cube,new Vector3(x*2-11,.03f,row*2),new Vector3(2,.035f,2),ModelLibrary.Material("Rush grid "+(x+row)%2,(x+row)%2==0?Color.white:Color.black));}
 }
 public class RushHazard:MonoBehaviour {
  public TrackWorld track;public int kind;public float phase;public bool active;Renderer warning;Game game;float rockTimer;readonly Dictionary<Vehicle,float> cooldown=new Dictionary<Vehicle,float>();
  public void Build(){var m=new Material(Shader.Find("Aether/Toon"));m.color=kind==0?new Color(.11f,.13f,.19f):new Color(1,.44f,.12f);var bed=TrackWorld.Cube("Warning lane",transform.position+Vector3.up*.035f,new Vector3(5.5f,.04f,15),m,false);bed.transform.SetParent(transform);warning=bed.GetComponent<Renderer>();for(int s=-1;s<=1;s+=2)CarParts.Part(transform,"Hazard lane edge",PrimitiveType.Cube,new Vector3(s*2.8f,.08f,0),new Vector3(.12f,.07f,15),ModelLibrary.Material("Hazard glow "+kind,kind==2?new Color(.3f,.6f,1):new Color(1,.4f,.1f),.7f));}
  void Update(){if(!game)game=FindAnyObjectByType<Game>();if(!game||!game.RaceSimulationActive)return;float cycle=Mathf.Repeat(game.raceTime+phase,6);active=kind==0||cycle>3;warning.material.color=active?(kind==2?new Color(.1f,.55f,1):kind==1?new Color(1,.28f,.07f):new Color(.065f,.075f,.1f)):new Color(.45f,.28f,.08f)*( .7f+.3f*Mathf.Sin(cycle*9));if(kind==1&&active&&Time.time>rockTimer&&game.player&&Mathf.Abs(game.player.transform.position.z-transform.position.z)<170){rockTimer=Time.time+3;var rock=GameObject.CreatePrimitive(PrimitiveType.Sphere);rock.name="Falling canyon boulder";rock.transform.SetParent(track.transform);rock.transform.position=transform.position+Vector3.up*22;rock.transform.localScale=Vector3.one*2.6f;rock.GetComponent<Renderer>().sharedMaterial=ModelLibrary.Material("Falling stone",new Color(.4f,.21f,.12f));var body=rock.AddComponent<Rigidbody>();body.mass=900;body.collisionDetectionMode=CollisionDetectionMode.ContinuousDynamic;Destroy(rock,6);}
   if(!active)return;foreach(var v in game.racers){var p=transform.InverseTransformPoint(v.transform.position);if(v.finished||Mathf.Abs(p.x)>2.8f||Mathf.Abs(p.z)>7.5f||p.y>3||p.y< -1)continue;if(cooldown.TryGetValue(v,out float next)&&Time.time<next)continue;cooldown[v]=Time.time+3;if(kind==0){if(v.shield>0)v.shield=0;else v.oilFor=2.5f;}else if(kind==2){if(v.shield>0)v.shield=0;else{v.empFor=2;v.Hit(Vector3.up*3);}}if(v.player)game.Toast(kind==0?"Oil trap · grip reduced":kind==2?"Electric lane · boost interrupted":"Falling rocks · change lanes");}
  }
  void OnDestroy(){if(warning)Destroy(warning.sharedMaterial);}
 }
 public class RushTrafficSystem:MonoBehaviour {
  public TrackWorld track;Game game;readonly List<Rigidbody> cars=new List<Rigidbody>();readonly List<float> lanes=new List<float>(),speeds=new List<float>();
  void Start(){game=FindAnyObjectByType<Game>();for(int i=0;i<18;i++){var root=new GameObject("Rush traffic "+i);root.transform.SetParent(transform);root.layer=10;var model=ModelLibrary.Create(CarSpec.All[(i+2)%10].name,root.transform);float lane=new[]{-9f,-3f,3f,9f}[i%4];float speed=i%3==0?19:-15-i%5;root.transform.SetPositionAndRotation(new Vector3(lane,5.12f,170+i*92),Quaternion.Euler(0,speed<0?180:0,0));var col=root.AddComponent<BoxCollider>();col.center=new Vector3(0,.65f,0);col.size=new Vector3(1.9f,1,4.3f);var body=root.AddComponent<Rigidbody>();body.mass=240;body.angularDamping=.5f;body.maxAngularVelocity=18;root.AddComponent<RushTrafficBody>();body.collisionDetectionMode=CollisionDetectionMode.ContinuousDynamic;body.interpolation=RigidbodyInterpolation.Interpolate;cars.Add(body);lanes.Add(lane);speeds.Add(speed);CarParts.Apply(model,new SavedCar{body=(i+2)%10,paint=i*3%32});}}
  void FixedUpdate(){if(!game||!game.player)return;for(int i=0;i<cars.Count;i++){var body=cars[i];if(!game.RaceSimulationActive){body.linearVelocity=Vector3.zero;continue;}var damage=body.GetComponent<RushTrafficBody>();if(damage.disabled)continue;var p=body.position;float z=game.player.transform.position.z;bool outOfRange=p.z<z-150||p.z>z+1800||p.y<2||Mathf.Abs(p.x)>13;
    if(outOfRange){float ahead=z+400+i*57;if(ahead>track.length-25)continue;var target=new Vector3(lanes[i],5.12f,ahead);if(Physics.CheckBox(target+Vector3.up*.6f,new Vector3(1.2f,.7f,3),Quaternion.identity,1<<8))continue;body.position=target;body.rotation=Quaternion.Euler(0,speeds[i]<0?180:0,0);p=target;}
    if(Vector3.Dot(body.transform.up,Vector3.up)<.55f){damage.DisableDrive();continue;}var desired=new Vector3(Mathf.Clamp((lanes[i]-p.x)*2,-2,2),0,speeds[i]);body.AddForce(Vector3.ClampMagnitude((desired-Vector3.ProjectOnPlane(body.linearVelocity,Vector3.up))*3,18),ForceMode.Acceleration);body.AddTorque(Vector3.Cross(body.transform.up,Vector3.up)*5-body.angularVelocity*2,ForceMode.Acceleration);
   }}
 }
}
