using System;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEngine;
namespace Aether {
 public class StuntTest:MonoBehaviour {
  Game game;int failures;float began;string output;bool drive;float nextReport;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){if(Environment.GetCommandLineArgs().Contains("-aetherStuntTest"))new GameObject("Stunt verification").AddComponent<StuntTest>();}
  void Check(bool ok,string name){Debug.Log("STUNT "+(ok?"PASS ":"FAIL ")+name);if(!ok)failures++;}
  void Update(){if(began>0&&Time.realtimeSinceStartup-began>330){File.WriteAllText(Path.Combine(output,"test-result.txt"),"TIMEOUT failures="+failures);Application.Quit(2);}if(!drive||!game||!game.player)return;var v=game.player;v.throttle=v.grounded>=2?1:Mathf.Clamp(Mathf.Asin(Mathf.Clamp(v.transform.forward.y,-1,1))*2,-1,1);float aim=TrackWorld.StuntX(v.transform.position.z+35);v.steer=v.grounded>=2?Mathf.Clamp((aim-v.transform.position.x)*.015f-v.body.linearVelocity.x*.035f-Vector3.SignedAngle(Vector3.forward,Vector3.ProjectOnPlane(v.transform.forward,Vector3.up),Vector3.up)*.02f,-.35f,.35f):0;if(Time.time>nextReport){nextReport=Time.time+2;Debug.Log("STUNT DRIVE p="+v.transform.position+" vel="+v.body.linearVelocity+" up="+v.transform.up+" ground="+v.grounded+" checkpoint="+v.stuntCheckpoint+" returns="+v.automaticReturns);}}
  IEnumerator Shot(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return null;}
  void Place(Vehicle v,Vector3 p,Quaternion q){v.body.position=p;v.transform.SetPositionAndRotation(p,q);v.body.rotation=q;v.body.linearVelocity=v.body.angularVelocity=Vector3.zero;v.shield=v.stun=v.rolloverLock=0;v.offTrackTime=v.wrongWayTime=v.trappedTime=0;Physics.SyncTransforms();}
  IEnumerator Start(){output=Path.GetFullPath(Application.dataPath+"/../../Evidence/Stunts");Directory.CreateDirectory(output);began=Time.realtimeSinceStartup;yield return new WaitForSeconds(1);game=FindAnyObjectByType<Game>();game.ChooseDevice(false);game.menu="Store";yield return new WaitForSeconds(1);yield return Shot("01-store");
   foreach(int i in new[]{6,7,8,9}){game.SelectStoreProduct(i);yield return new WaitForSeconds(.25f);yield return Shot("02-product-"+SupportStore.Products[i].id);}
   Check(SupportStore.Products.Length==10&&SupportStore.Products.Select(p=>p.id).Distinct().Count()==10,"Ten unique products");foreach(var p in SupportStore.Products){var c=SupportStore.PreviewCar(p);Check(SupportStore.Bonus(c,true).sqrMagnitude>0,"Product bonus "+p.id);Check(SupportStore.Bonus(c)==Vector4.zero||SupportStore.Owned(p.id),"Unowned bonus rejected "+p.id);}
   var save=new SavedCar{glassWheels=true,glassChassis=true,supportEdition="vanta-gold"};var loaded=JsonUtility.FromJson<SavedCar>(JsonUtility.ToJson(save));Check(loaded.glassWheels&&loaded.glassChassis&&loaded.supportEdition=="vanta-gold","Glass and edition serialization");
   game.menu="Play";game.stuntTab=true;yield return Shot("03-stunts-menu");game.StartRush(0);yield return new WaitUntil(()=>game.state==Game.State.Race);var car=game.player;car.manualTest=true;car.enforceTrackBounds=false;foreach(var v in game.racers){v.manualTest=true;v.throttle=0;}
   TrackWorld.Cube("Impact test ground",new Vector3(1700,-.2f,0),new Vector3(200,.4f,800),ModelLibrary.Material("Test ground",Color.gray),true);
   Place(car,new Vector3(1700,.2f,0),Quaternion.identity);yield return new WaitForSeconds(.2f);car.item="Shield";car.UseItem();yield return new WaitForFixedUpdate();Check(Mathf.Abs(car.body.mass-car.spec.mass*2)<1,"Shield doubles actual rigidbody mass");car.shield=0;yield return new WaitForFixedUpdate();Check(Mathf.Abs(car.body.mass-car.spec.mass)<1,"Mass restores after shield");
   var victim=game.racers[1];victim.enforceTrackBounds=false;Place(victim,new Vector3(1700,.2f,6),Quaternion.identity);car.item="Pulse";car.UseItem();Check(victim.rolloverLock>=1.49f&&victim.stun>=1.49f,"Pulse applies 1.5-second rollover lock and stun");yield return new WaitForFixedUpdate();Check(victim.body.linearVelocity.magnitude>30,"Close Pulse produces strong launch");Check(Vehicle.PulseStrength(4)>Vehicle.PulseStrength(18)*1.5f,"Pulse weakens with distance");float lockTime=victim.rolloverLock;game.PauseRace();yield return new WaitForSecondsRealtime(.2f);Check(Mathf.Abs(lockTime-victim.rolloverLock)<.001f,"Pause preserves stun timer");game.HandleBack();yield return new WaitForSeconds(1.55f);Check(victim.rolloverLock==0,"Rollover resumes after lock");
   var traffic=game.track.GetComponentsInChildren<RushTrafficBody>().First();var tb=traffic.GetComponent<Rigidbody>();Check(tb.mass<car.body.mass*.35f&&tb.constraints==RigidbodyConstraints.None,"Rush traffic light and rotation unlocked");traffic.disabledUntil=Time.time+.7f;tb.position=new Vector3(1700,.3f,12);tb.rotation=Quaternion.Euler(0,180,0);tb.linearVelocity=Vector3.zero;Place(car,new Vector3(1700,.2f,0),Quaternion.identity);car.body.linearVelocity=Vector3.forward*40;yield return new WaitForSeconds(.5f);Check(traffic.disabled&&tb.linearVelocity.magnitude>20&&tb.position.y>1.3f,"Physical car collision throws traffic and suspends driving");yield return Shot("04-traffic-impact");
   var citizenRoot=new GameObject("Collision test resident");citizenRoot.transform.position=new Vector3(1700,0,80);CarParts.Part(citizenRoot.transform,"Torso",PrimitiveType.Capsule,Vector3.up,new Vector3(.5f,.8f,.4f),ModelLibrary.Material("Citizen test",Color.red));var person=citizenRoot.AddComponent<CityPedestrian>();person.Initialize();Place(car,new Vector3(1700,.2f,70),Quaternion.identity);car.body.linearVelocity=Vector3.forward*28;yield return new WaitForSeconds(.6f);Check(person.struck&&person.body.linearVelocity.magnitude>12,"Vehicle physically strikes pedestrian");yield return Shot("05-pedestrian-impact");Destroy(citizenRoot);
   Place(car,new Vector3(1700,.2f,200),Quaternion.identity);var mineObject=new GameObject("Persistent test mine");mineObject.transform.SetParent(game.track.transform);mineObject.transform.position=new Vector3(1730,.1f,200);var mine=mineObject.AddComponent<WeaponHazard>();mine.Initialize(game,car,true);yield return new WaitForSeconds(13);Check(mine,"Untriggered mine survives past old 12-second expiry");Place(victim,new Vector3(1730,.2f,205),Quaternion.identity);yield return new WaitForSeconds(1.2f);Check(!mine,"Mine removed after proximity detonation");
   game.stuntAiCount=0;game.StartStunts();yield return new WaitUntil(()=>game.state==Game.State.Race);car=game.player;car.manualTest=true;Check(game.track.isStunts&&!game.rushMode&&game.racers.Count==1,"STUNTS supports zero opponents");Check(TrackWorld.StuntHeight(100)-TrackWorld.StuntHeight(1150)==1000,"First descent drops one kilometre");Check(!Physics.Raycast(new Vector3(0,900,1700),Vector3.down,500),"First jump has a real road gap");Check(game.track.stuntTiles.Select(t=>t.kind).Distinct().Count()==5,"Five functional tile types");yield return Shot("06-heartstopper-start");
   drive=true;float started=Time.realtimeSinceStartup;bool shotAir=false,shotLanding=false;while(!car.finished&&Time.realtimeSinceStartup-started<150){if(car.transform.position.z>1510&&!shotAir){shotAir=true;yield return Shot("07-first-jump");}if(car.stuntCheckpoint>=3&&!shotLanding){shotLanding=true;yield return Shot("08-second-descent");}yield return null;}drive=false;Check(car.finished,"Continuous physics-driven Heartstopper run reaches finish");if(car.finished){int credits=game.credits;game.OnFinish(car);Check(credits==game.credits,"Finish reward cannot be awarded twice");yield return new WaitForSecondsRealtime(3);yield return Shot("09-stunt-results");}
   game.StartStunts();yield return new WaitUntil(()=>game.state==Game.State.Race);car=game.player;car.manualTest=true;car.stuntCheckpoint=3;Place(car,new Vector3(300,200,2800),Quaternion.identity);car.Recover();Check(car.transform.position.z<2350&&car.transform.position.z>2300&&car.stuntCheckpoint==3,"Recovery uses earned checkpoint without skipping progress");game.ChooseDevice(true);yield return Shot("10-phone-stunts");game.ChooseDevice(false);
   File.WriteAllText(Path.Combine(output,"test-result.txt"),"failures="+failures);Debug.Log("STUNT COMPLETE failures="+failures);Application.Quit(failures==0?0:1);
  }
 }
}
