from pathlib import Path
root=Path(__file__).resolve().parents[1]
def edit(file,old,new):
 p=root/file;s=p.read_text(encoding='utf-8-sig');assert old in s,(file,old[:90]);p.write_text(s.replace(old,new),encoding='utf-8')
v='Assets/Scripts/Vehicle.cs'
edit(v,'bool active=game.state==Game.State.Race;if(empFor>0)boost=0;','bool active=game.state==Game.State.Race;RefreshShieldMass();if(active)rolloverLock=Mathf.Max(0,rolloverLock-Time.fixedDeltaTime);if(empFor>0)boost=0;')
edit(v,'if(active&&upright<.2f&&overturned>.10f)','if(active&&rolloverLock<=0&&upright<.2f&&overturned>.10f)')
edit(v,'if(active&&righting>0)','if(active&&rolloverLock<=0&&righting>0)')
edit(v,'if(rollGrace<=0)body.AddTorque','if(rollGrace<=0&&rolloverLock<=0)body.AddTorque')
edit(v,'compression*(carIndex==3?30000:36000)-Vector3.Dot(velocity,transform.up)*4200,0,26000','(compression*(carIndex==3?30000:36000)-Vector3.Dot(velocity,transform.up)*4200)*(body.mass/spec.mass),0,26000*(body.mass/spec.mass)')
edit(v,'shield=8;','shield=8;RefreshShieldMass();')
edit(v,'CityPhysics.Blast(transform.position,22,20);game.Burst(transform.position,new Color(.4f,1,1),3);foreach(var v in game.racers)if(v!=this&&Vector3.Distance(v.transform.position,transform.position)<22)v.Hit((v.transform.position-transform.position).normalized*8);','CityPhysics.Blast(transform.position,22,58);RaceEffects.Ring(transform.position,Color.cyan,22);game.Burst(transform.position,new Color(.4f,1,1),3);foreach(var v in game.racers)if(v!=this&&Vector3.Distance(v.transform.position,transform.position)<22)v.PushHit((v.transform.position-transform.position).normalized*PulseStrength(Vector3.Distance(v.transform.position,transform.position))+Vector3.up*7);')
edit(v,'if(shield>0){shield=0;','if(shield>0){shield=0;RefreshShieldMass();')
edit(v,'void OnCollisionEnter(Collision c){if(game==null','void OnCollisionEnter(Collision c){if(game!=null)ImpactCollision(c);if(game==null')
edit(v,'Mathf.Min(8,(int)(impact/3)),5','Mathf.Min(28,(int)(impact)),Mathf.Min(18,impact*.55f)')
edit('Assets/Scripts/RaceEffects.cs','debrisCount<100','debrisCount<240')
edit('Assets/Scripts/PremiumWeapons.cs','if(age>12)','if(!mine&&age>12)')
edit('Assets/Scripts/PremiumWeapons.cs','shield=0;RaceEffects.Ring','shield=0;RefreshShieldMass();RaceEffects.Ring')
edit('Assets/Scripts/PremiumWorld.cs','seed%4==3?1450:1050','seed%4==3?310:220')
for old,new in [('1150,false,30','240,false,16'),('1800,false,30','380,false,18'),('230,false,24','120,false,14')]:edit('Assets/Scripts/PhilippineCity.cs',old,new)
edit('Assets/Scripts/CityLife.cs','people.Add((root,left,right,home,track.Forward(n),i*.7f));','root.gameObject.AddComponent<CityPedestrian>().Initialize();people.Add((root,left,right,home,track.Forward(n),i*.7f));')
edit('Assets/Scripts/CityLife.cs','foreach(var person in people){','foreach(var person in people){\n    var physics=person.root.GetComponent<CityPedestrian>();if(physics.struck)continue;')
edit('Assets/Scripts/CityLife.cs','person.root.position=pos;person.root.rotation=Quaternion.LookRotation(person.direction*(Mathf.Cos(t)>0?1:-1));','physics.Walk(pos,Quaternion.LookRotation(person.direction*(Mathf.Cos(t)>0?1:-1)));')
edit('Assets/Scripts/RushWorld.cs','body.mass=1300;body.constraints=RigidbodyConstraints.FreezeRotation;','body.mass=240;body.angularDamping=.5f;body.maxAngularVelocity=18;root.AddComponent<RushTrafficBody>();')
edit('Assets/Scripts/RushWorld.cs','var p=body.position;float z=','var damage=body.GetComponent<RushTrafficBody>();if(damage.disabled)continue;var p=body.position;float z=')
edit('Assets/Scripts/RushWorld.cs','body.linearVelocity=new Vector3(Mathf.Clamp((lanes[i]-p.x)*2,-2,2),body.linearVelocity.y,speeds[i]);','if(Vector3.Dot(body.transform.up,Vector3.up)<.55f){damage.DisableDrive();continue;}var desired=new Vector3(Mathf.Clamp((lanes[i]-p.x)*2,-2,2),0,speeds[i]);body.AddForce(Vector3.ClampMagnitude((desired-Vector3.ProjectOnPlane(body.linearVelocity,Vector3.up))*3,18),ForceMode.Acceleration);body.AddTorque(Vector3.Cross(body.transform.up,Vector3.up)*5-body.angularVelocity*2,ForceMode.Acceleration);')
edit('Assets/Scripts/CityPhysics.cs','foreach(var prop in affected)if(prop)prop.Push(p,radius,speed);','foreach(var prop in affected)if(prop)prop.Push(p,radius,speed);\n   var bodies=new HashSet<Rigidbody>();for(int i=0;i<count;i++){var body=overlaps[i].attachedRigidbody;if(!body||!bodies.Add(body))continue;float d=Vector3.Distance(body.worldCenterOfMass,p),f=Mathf.Clamp01(1-d/radius);var pedestrian=body.GetComponent<CityPedestrian>();if(pedestrian)pedestrian.Strike((body.worldCenterOfMass-p).normalized*speed*f+Vector3.up*8);var traffic=body.GetComponent<RushTrafficBody>();if(traffic){traffic.DisableDrive();body.AddForce((body.worldCenterOfMass-p).normalized*speed*f+Vector3.up*speed*.35f*f,ForceMode.VelocityChange);body.AddTorque(Random.insideUnitSphere*9,ForceMode.VelocityChange);}}')
edit('Assets/Scripts/TrackRecovery.cs','rollGrace=0;launchGrace=0;wet=false;','rollGrace=0;rolloverLock=0;launchGrace=0;wet=false;')
print('Integrated impact physics')
