exec((__import__('pathlib').Path(__file__).parent/'integrate_stunts.py').read_text().split("v='Assets/Scripts/Vehicle.cs'")[0])
edit('Assets/Scripts/SupportShop.cs','public string id,name,description,price;','public string id,name,description,price;')
edit('Assets/Scripts/SupportShop.cs','new SupportProduct("star-trail","Starlight trail","A violet particle trail while using boost.","1.99",-1,new Color(.7f,.4f,1))};','new SupportProduct("star-trail","Starlight trail","Violet boost particles with an acceleration upgrade.","1.99",-1,new Color(.7f,.4f,1)),\n   new SupportProduct("vanta-gold","Golden Vanta","Polished gold body, aero kit and the strongest Vanta engine.","9.99",0,new Color(1,.7f,.22f)),\n   new SupportProduct("vanta-chrome","Chrome Vanta","Mirror-finish body with upgraded brakes and high-speed grip.","7.99",0,new Color(.72f,.88f,1)),\n   new SupportProduct("glass-wheels","Glass wheels","Transparent cyan alloy rims with improved grip and braking.","2.99",-1,new Color(.3f,.9f,1)),\n   new SupportProduct("glass-chassis","Glass chassis","See-through body panels, visible frame and battery, plus a faster powertrain. Fits every car.","4.99",-1,new Color(.4f,1,.88f))};')
p=root/'Assets/Scripts/SupportShop.cs';s=p.read_text();start=s.index('  void SupportGUI(){');s=s[:start]+'  void SupportGUI(){StoreGUI();}\n }\n}\n';p.write_text(s)
edit('Assets/Scripts/CarParts.cs','public bool neonWheels,starTrail;','public bool neonWheels,starTrail,glassWheels,glassChassis;')
edit('Assets/Scripts/Vehicle.cs','spec=CarSpec.All[index];player=isPlayer;','spec=isPlayer?SupportStore.Tuned(CarSpec.All[index],g.CurrentCar):CarSpec.All[index];player=isPlayer;')
edit('Assets/Scripts/GarageUI.cs','var spec=CarSpec.All[c.body];','var spec=SupportStore.Tuned(CarSpec.All[c.body],c);')
for f in ['Assets/Scripts/GarageUI.cs','Assets/Scripts/RushUI.cs']:edit(f,'"Controls","Support"','"Controls","Store"');edit(f,'if(menu=="Support")','if(menu=="Store"||menu=="Support")')
edit('Assets/Editor/BuildGame.cs','var shaders=new[]{','var shaders=new[]{Shader.Find("Aether/StoreGlass"),')
edit('Assets/Scripts/RushUI.cs','if(menu=="Game Setup")rushMode=false;','if(menu=="Game Setup"){rushMode=false;stuntMode=false;}')
edit('Assets/Scripts/RushUI.cs','if(menu=="Game Setup"){rushMode=false;SetupGUI();','if(menu=="Game Setup"){rushMode=false;stuntMode=false;SetupGUI();')
edit('Assets/Scripts/RushUI.cs','if(Button("Rush Challenges",34,113,246,46,!circuitTab))circuitTab=false;if(Button("Circuit races",293,113,215,46,circuitTab))circuitTab=true;','if(Button("Rush Challenges",34,113,246,46,!circuitTab&&!stuntTab)){circuitTab=false;stuntTab=false;}if(Button("Circuit races",293,113,215,46,circuitTab&&!stuntTab)){circuitTab=true;stuntTab=false;}if(Button("STUNTS",521,113,216,46,stuntTab))stuntTab=true;\n   if(stuntTab){StuntHomeGUI();return;}')
edit('Assets/Scripts/RushUI.cs','{rushMode=false;StartRace();}','{rushMode=false;stuntMode=false;StartRace();}')
edit('Assets/Scripts/RushInventory.cs','rushMode=true;StartRace();','rushMode=true;stuntMode=false;StartRace();')
g='Assets/Scripts/Game.cs'
edit(g,'RushReset();track=new GameObject(rushMode?Challenge.name:TrackWorld.Names[mapIndex]).AddComponent<TrackWorld>();if(rushMode)','RushReset();track=new GameObject(stuntMode?"Heartstopper":rushMode?Challenge.name:TrackWorld.Names[mapIndex]).AddComponent<TrackWorld>();if(stuntMode)track.GenerateStunts();else if(rushMode)')
edit(g,'i<=(rushMode?Challenge.opponents:aiCount)','i<=(stuntMode?0:rushMode?Challenge.opponents:aiCount)')
edit(g,'int n=rushMode?0:','int n=stuntMode||rushMode?0:')
edit(g,'Vector3 p=rushMode?new Vector3','Vector3 p=stuntMode?track.StuntPosition(0)+Vector3.up*.55f:rushMode?new Vector3')
edit(g,'track.ConnectFeatures(this);ApplyDeviceQuality();','track.ConnectFeatures(this);ApplyDeviceQuality();cam.farClipPlane=stuntMode?10000:3000;')
edit(g,'if(powerups||rushMode)','if(powerups||rushMode||stuntMode)')
edit(g,'public void OnFinish(Vehicle v){if(rushMode)','public void OnFinish(Vehicle v){if(stuntMode){AwardStunts(v);return;}if(rushMode)')
edit(g,'else if(rushMode)RushRaceGUI();','else if(stuntMode)StuntRaceGUI();else if(rushMode)RushRaceGUI();')
edit(g,'Shield · absorbs one hit','Shield · double mass, forceful impacts')
edit('Assets/Scripts/TrackWorld.cs','public Vector3 Forward(int i)=>isRush?','public Vector3 Forward(int i)=>isStunts?(StuntPosition(Mathf.Clamp(i,0,Count-1)*length/(Count-1)+1)-StuntPosition(Mathf.Clamp(i,0,Count-1)*length/(Count-1)-1)).normalized:isRush?')
edit('Assets/Scripts/TrackWorld.cs','Nearest(Vector3 p){if(isRush)','Nearest(Vector3 p){if(isRush||isStunts)')
edit('Assets/Scripts/TrackFeatures.cs','public bool Broken(int i)=>isRush?','public bool Broken(int i)=>isRush||isStunts?')
edit('Assets/Scripts/TrackRecovery.cs','if(isRush)return Mathf.Abs(position.x)','if(isStunts)return StuntCorridor(position);\n   if(isRush)return Mathf.Abs(position.x)')
edit('Assets/Scripts/TrackRecovery.cs','int near=Nearest(car.transform.position);if(isRush)','if(isStunts){float z=car.stuntCheckpoint<=0?0:StuntGates[Mathf.Min(car.stuntCheckpoint-1,4)]-12;position=StuntPosition(z)+Vector3.up*.7f;point=Nearest(position);rotation=Quaternion.LookRotation(Forward(point));return;}\n   int near=Nearest(car.transform.position);if(isRush)')
edit('Assets/Scripts/Vehicle.cs','if(Mathf.Abs(delta)<20&&track.InRaceCorridor','if(!track.isStunts&&Mathf.Abs(delta)<20&&track.InRaceCorridor')
edit('Assets/Scripts/Vehicle.cs','if(!finished&&(track.isRush?','if(track.isStunts)StuntProgress();\n   if(!track.isStunts&&!finished&&(track.isRush?')
edit('Assets/Scripts/Vehicle.cs','if(active&&rolloverLock<=0&&upright<.2f','if(active&&(!track.isStunts||grounded>0)&&rolloverLock<=0&&upright<.2f')
edit('Assets/Scripts/Vehicle.cs','var emission=smoke.emission;emission.rateOverTime=active','if(active)StuntPhysics();\n   var emission=smoke.emission;emission.rateOverTime=active')
edit('Assets/Scripts/StuntWorld.cs','Presentation.Probe(transform,new Vector3(0,1604,30));','Presentation.Probe(transform,new Vector3(0,1604,30));CombineRushSector(transform);')
print('Integrated Store and STUNTS')
